import Link from 'next/link';
import {requirePlatformAdmin} from '@/lib/admin';
import {prisma} from '@/lib/prisma';
import {catalogCategoryLabel,CATALOG_CATEGORIES} from '@/lib/catalogTemplates';
import {directoryParams} from '@/lib/adminReadiness';
import {ConsoleHeader,Metric,Pager} from '../_components/Console';
import CatalogImage from './CatalogImage';
export const dynamic='force-dynamic';
export default async function CatalogReadiness({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 await requirePlatformAdmin('catalog');const {q,status,page:requested,pageSize}=directoryParams(await searchParams);
 const templates=await prisma.catalogTemplate.findMany({orderBy:[{categoryKey:'asc'},{sortOrder:'asc'},{id:'asc'}],select:{id:true,name:true,slug:true,categoryKey:true,imageUrl:true,description:true,isActive:true}});
 const complete=(t:(typeof templates)[number])=>Boolean(t.imageUrl?.trim()&&t.description?.trim());
 const rows=templates.filter(t=>(!q||`${t.name} ${catalogCategoryLabel(t.categoryKey)}`.toLowerCase().includes(q.toLowerCase()))&&(!status||(status==='ready'&&complete(t))||(status==='missing-photo'&&!t.imageUrl?.trim())||(status==='missing-description'&&!t.description?.trim())));
 const page=Math.min(requested,Math.max(1,Math.ceil(rows.length/pageSize)));
 return <div className="space-y-6"><ConsoleHeader eyebrow="Platform catalog" title="Catalog readiness">Review actual template photos and descriptions, then edit the missing details. Templates are a starting point—not a claim about any tenant’s owned equipment or rental prices.</ConsoleHeader><div className="grid gap-3 sm:grid-cols-3"><Metric label="Templates with photo + description" value={templates.filter(complete).length} detail={`${templates.length} total active and archived template records`}/><Metric label="Missing photo" value={templates.filter(t=>!t.imageUrl?.trim()).length} detail="Missing artwork stays visible here; it is not replaced with an unrelated photo"/><Metric label="Missing description" value={templates.filter(t=>!t.description?.trim()).length} detail="Custom template content is preserved during media initialization"/></div>
  <form aria-label="Catalog readiness filters" className="grid grid-cols-1 items-end gap-4 rounded-xl border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_200px_auto_auto]">
   <label className="block min-w-0 text-sm">Search templates<input aria-label="Search templates" name="q" defaultValue={q} className="mt-2 block w-full rounded-lg border p-3" placeholder="Equipment or category"/></label>
   <label className="block min-w-0 text-sm">Coverage<select aria-label="Catalog coverage" name="status" defaultValue={status} className="mt-2 block w-full rounded-lg border bg-white p-3"><option value="">All templates</option><option value="ready">Photo + description</option><option value="missing-photo">Missing photo</option><option value="missing-description">Missing description</option></select></label>
   <button className="w-full rounded-lg bg-slate-950 px-4 py-3 text-sm font-bold text-white">Apply filters</button><Link href="/admin/catalog-templates" className="block rounded-lg border px-4 py-3 text-center text-sm font-bold">Manage catalog</Link>
  </form>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.slice((page-1)*pageSize,page*pageSize).map(t=><article key={t.id} className="overflow-hidden rounded-2xl border bg-white"><CatalogImage name={t.name} src={t.imageUrl}/><div className="p-4"><p className="text-xs text-slate-500">{catalogCategoryLabel(t.categoryKey)} · {t.isActive?'active':'archived'}</p><h2 className="mt-2 text-base font-bold">{t.name}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{t.description?.trim()||'No description saved.'}</p><Link href={`/admin/catalog-templates?q=${encodeURIComponent(t.name)}`} className="mt-4 inline-block rounded-lg border px-3 py-2 text-sm font-bold text-blue-600">Edit template</Link></div></article>)}</section>{!rows.length&&<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">No templates match these filters.</p>}<Pager base="/admin/catalog-readiness" page={page} pageSize={pageSize} total={rows.length} q={q} status={status}/><details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer text-sm font-bold">Category coverage</summary><div className="mt-4 grid gap-3 sm:grid-cols-2">{CATALOG_CATEGORIES.map(c=>{const entries=templates.filter(t=>t.categoryKey===c.key);return <p className="text-sm" key={c.key}><b>{c.label}</b> · {entries.filter(complete).length} of {entries.length} with photo + description</p>})}</div></details></div>;
}
