import Link from "next/link";
import type { ReactNode } from "react";
import Icon, {type IconName} from "./Icon";
export function PageHeading({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description:string;actions?:ReactNode}){return <div className="tenant-page-heading"><div>{eyebrow&&<p className="tenant-eyebrow">{eyebrow}</p>}<h1>{title}</h1><p className="mt-1 max-w-2xl text-[13px] leading-5 text-slate-500">{description}</p></div>{actions&&<div className="flex flex-wrap items-center gap-2">{actions}</div>}</div>}
export function MetricCard({label,value,detail,icon,href}:{label:string;value:string|number;detail:string;icon:IconName;href?:string}){const tone=icon==="box"?"blue":icon==="orders"?"amber":"green";const content=<><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold text-slate-500">{label}</span><span className="rounded-lg bg-emerald-50 p-1.5 text-emerald-700"><Icon name={icon} className="h-[18px] w-[18px]"/></span></div><div className="mt-2 text-[24px] font-bold tracking-tight text-slate-950 tabular-nums">{value}</div><p className="mt-0.5 text-[11px] leading-4 text-slate-500">{detail}</p></>;return href?<Link href={href} className={"tenant-metric tenant-metric-"+tone+" transition"}>{content}</Link>:<div className={"tenant-metric tenant-metric-"+tone}>{content}</div>}
export function StatusBadge({status}:{status:string}){const tone=({confirmed:"green",active:"green",completed:"slate",cancelled:"red",pending:"amber",quote:"blue",available:"green",damaged:"red",needs_repair:"amber"} as Record<string,string>)[status]||"slate";return <span className={"tenant-badge tenant-badge-"+tone}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{status.replaceAll("_"," ")}</span>}
export function EmptyState({icon="box",title,description,href,label}:{icon?:IconName;title:string;description:string;href?:string;label?:string}){return <div className="px-6 py-12 text-center"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon name={icon}/></div><h3 className="font-semibold text-slate-900">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">{description}</p>{href&&<Link className="tenant-button tenant-button-primary mt-5" href={href}>{label}<Icon name="arrow" className="h-4 w-4"/></Link>}</div>}
export function SectionHeading({title,description,href,label="View all"}:{title:string;description?:string;href?:string;label?:string}){return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-4 py-3"><div><h2 className="text-sm font-bold text-slate-900">{title}</h2>{description&&<p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>}</div>{href&&<Link href={href} className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-700 hover:text-emerald-900">{label}<Icon name="arrow" className="h-3.5 w-3.5"/></Link>}</div>}
export const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
export const eventDateLabel=(date:Date|string)=>new Date(date).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"});
