import {redirect} from 'next/navigation';
import {getPlatformAdminAccess} from '@/lib/admin';
import Link from "next/link";
import {prisma} from "@/lib/prisma";
import {requirePlatformAdmin} from "@/lib/admin";
import Icon from "@/app/dashboard/components/Icon";
import {ConsoleHeader,Metric,Empty} from "./_components/Console";
export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map(word=>word[0]||"").join("").toUpperCase()||"PR";
export default async function PlatformOverviewPage(){
  const accessSession=await requirePlatformAdmin('console');
 const accessRole=await getPlatformAdminAccess((accessSession.user as {id:string}).id);if(accessRole==='catalog')redirect('/admin/catalog-templates');
 await requirePlatformAdmin('overview');
  const scope={organization:{slug:{not:"_platform_internal"}}};
  const [orgs,orders,customers,users,activity]=await Promise.all([
    prisma.organization.findMany({where:{slug:{not:"_platform_internal"}},orderBy:[{createdAt:"desc"},{id:"asc"}],select:{id:true,name:true,slug:true,status:true,createdAt:true,subscription:{select:{status:true}},_count:{select:{orders:true}}}}),
    prisma.order.aggregate({where:{...scope,status:{notIn:["cancelled","canceled"]}},_sum:{totalAmount:true,amountPaid:true},_count:{_all:true}}),
    prisma.customer.count({where:scope}),prisma.user.count({where:{...scope,role:{not:"platform_admin"}}}),
    prisma.auditLog.findMany({orderBy:{createdAt:"desc"},take:8,select:{id:true,organizationId:true,action:true,createdAt:true}}),
  ]);
  const names=new Map(orgs.map(o=>[o.id,o.name]));
  const attention=orgs.filter(o=>o.status==="suspended"||["past_due","unpaid","trial_ended"].includes(o.subscription?.status||"")).length;
  const week=Date.now()-7*86400000,newAccounts=orgs.filter(o=>o.createdAt.getTime()>=week).length;
  return <div className="space-y-6">
    <ConsoleHeader eyebrow="Platform overview" title="Control center">A clear view of your rental companies, account activity, and the next steps that need your attention.</ConsoleHeader>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon="box" label="Tenant organizations" value={orgs.length} detail={`${orgs.filter(o=>o.status==="active").length} active accounts · internal account excluded`}/><Metric icon="wallet" label="Active subscriptions" value={orgs.filter(o=>o.subscription?.status==="active").length} detail="Local subscription records; successful payment is not independently verified."/><Metric icon="users" label="Tenant staff" value={users} detail={`${customers.toLocaleString()} customer records across tenant accounts`}/><Metric icon="orders" label="Tenant order value" value={money(orders._sum.totalAmount||0)} detail={`${orders._count._all} non-canceled orders · not platform subscription revenue`}/></section>
    <section className="grid gap-3 lg:grid-cols-3" aria-label="Platform priorities">
      <Link href="/admin/alerts" className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-amber-700"><Icon name="clock"/></span><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">Account review</h2><p className="mt-1 text-xs text-slate-500">{attention} suspended or billing-blocked accounts</p></div><Icon name="arrow" className="h-4 w-4 shrink-0 text-slate-400"/></Link>
      <Link href="/admin/onboarding" className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon name="check"/></span><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">Help new tenants get started</h2><p className="mt-1 text-xs text-slate-500">{newAccounts} accounts created in the last 7 days</p></div><Icon name="arrow" className="h-4 w-4 shrink-0 text-slate-400"/></Link>
      <Link href="/admin/users" className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><Icon name="users"/></span><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">Open a tenant workspace</h2><p className="mt-1 text-xs text-slate-500">Find a user and start an audited support view</p></div><Icon name="arrow" className="h-4 w-4 shrink-0 text-slate-400"/></Link>
    </section>
    <section className="grid items-start gap-5 xl:grid-cols-[1.3fr_1fr]">
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="text-base font-semibold">Newest tenants</h2><p className="mt-1 text-xs text-slate-500">Your most recently created rental businesses.</p></div><Link href="/admin/organizations" className="text-xs font-semibold text-blue-600">All organizations →</Link></div><div className="divide-y divide-slate-100">{orgs.slice(0,6).map(o=><Link key={o.id} href={`/admin/organizations/${o.id}`} className="flex items-center justify-between gap-3 px-5 py-4 hover:bg-slate-50"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 text-xs font-semibold text-slate-600">{initials(o.name)}</span><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{o.name}</h3><p className="mt-1 truncate text-xs text-slate-500">{o.slug}</p></div></div><div className="shrink-0 text-right"><span className={`inline-flex rounded-md px-2 py-1 text-[11px] font-semibold ${o.status==="active"?"bg-emerald-50 text-emerald-700":o.status==="suspended"?"bg-rose-50 text-rose-700":"bg-slate-100 text-slate-600"}`}>{o.status}</span><p className="mt-1 text-[11px] text-slate-500">{o._count.orders} orders</p></div></Link>)}{!orgs.length&&<Empty>No tenant organizations yet. Create an account to start onboarding a rental business.</Empty>}</div></div>
      <div className="space-y-5"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="text-base font-semibold">Recent activity</h2><p className="mt-1 text-xs text-slate-500">Administrative changes recorded in the audit log.</p></div><div className="divide-y divide-slate-100">{activity.map(a=><div key={a.id} className="flex items-start gap-3 px-5 py-3.5"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-400"/><div className="min-w-0"><p className="break-words text-xs font-semibold" title={a.action}>{a.action.replaceAll("_"," ").replaceAll("."," › ")}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{a.organizationId?(names.get(a.organizationId)||"Tenant"):"Platform"} · {a.createdAt.toISOString().replace("T"," ").slice(0,16)} UTC</p></div></div>)}{!activity.length&&<Empty>No administrative activity recorded yet. Account and support changes appear here as you work.</Empty>}</div><div className="border-t border-slate-100 p-3"><Link href="/admin/audit-log" className="block rounded-lg py-2 text-center text-xs font-semibold text-blue-600 hover:bg-slate-50">Search audit history →</Link></div></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><Icon name="shield" className="h-5 w-5 text-blue-600"/><h2 className="mt-3 text-sm font-semibold text-slate-800">The right context for every change</h2><p className="mt-2 text-xs leading-6 text-slate-600">This console manages the platform. Use tenant support to see a business’s own workspace, with a visible support banner and their actual permissions.</p><Link href="/admin/integrations" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-blue-600">Review tenant connections<Icon name="arrow" className="h-4 w-4"/></Link></div></div>
    </section>
  </div>;
}
