const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {createRequire}=require('node:module');
function load(file,mocks={}){const name=path.resolve(file),module={exports:{}};const code=ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const native=createRequire(name),req=n=>Object.hasOwn(mocks,n)?mocks[n]:n.startsWith('@/')?load(n.slice(2)+'.ts',mocks):native(n);vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:name})(req,module,module.exports);return module.exports;}
const {recurringRunRate}=load('lib/recurringRevenue.ts');
function subscription(overrides={}){return {status:'active',livemode:true,currency:'usd',items:{data:[{quantity:2,price:{id:'price1',currency:'usd',unit_amount:10000,billing_scheme:'per_unit',product:'prod1',recurring:{interval:'month',interval_count:1,usage_type:'licensed'}}}]},...overrides};}
test('contractual price and quantity, not current marketing price, determine run-rate',()=>{assert.equal(recurringRunRate(subscription()).netMonthlyCents,20000)});
test('annual and multi-month intervals are normalized',()=>{const s=subscription();s.items.data[0].price.recurring={interval:'year',interval_count:2};assert.equal(recurringRunRate(s).netMonthlyCents,20000/24)});
test('recurring percent and fixed discounts reduce current run-rate',()=>{const s=subscription({discounts:[{id:'d1',coupon:{duration:'forever',percent_off:25}},{id:'d2',coupon:{duration:'repeating',amount_off:1000,currency:'usd'}}]});assert.equal(recurringRunRate(s).netMonthlyCents,14000)});
test('one-time and expired discounts are excluded from recurring discounts',()=>{const s=subscription({discounts:[{coupon:{duration:'once',percent_off:50}},{end:1,coupon:{duration:'forever',percent_off:80}}]});assert.equal(recurringRunRate(s).netMonthlyCents,20000)});
test('unknown/unexpanded discount is excluded instead of presented as zero revenue',()=>{assert.equal(recurringRunRate(subscription({discounts:['di_unexpanded']})).netMonthlyCents,null)});
test('different-currency amount discounts require manual reconciliation',()=>{assert.ok(recurringRunRate(subscription({discount:{coupon:{duration:'forever',amount_off:500,currency:'eur'}}})).exclusion)});
for(const overrides of [{livemode:false},{status:'past_due'},{status:'canceled'},{pause_collection:{behavior:'void'}}])test('run-rate excludes '+JSON.stringify(overrides),()=>assert.equal(recurringRunRate(subscription(overrides)).netMonthlyCents,null));
test('tiered, metered, missing quantities and nonfinite amounts are unvalued',()=>{for(const patch of [{billing_scheme:'tiered'},{unit_amount:Infinity},{transform_quantity:{divide_by:10}},{recurring:{interval:'month',interval_count:1,usage_type:'metered'}}]){const s=subscription();Object.assign(s.items.data[0].price,patch);assert.ok(recurringRunRate(s).exclusion)}const s=subscription();delete s.items.data[0].quantity;assert.ok(recurringRunRate(s).exclusion)});
test('zero-dollar contractual amount is preserved as a real zero',()=>{const s=subscription();s.items.data[0].price.unit_amount=0;assert.equal(recurringRunRate(s).netMonthlyCents,0)});
const roles=load('lib/platformCapabilities.ts');
test('all named platform roles are explicit and unknown roles fail closed',()=>{assert.equal(roles.platformAllows('unexpected','console'),false);assert.equal(roles.platformAllows('catalog','catalog'),true);assert.equal(roles.platformAllows('catalog','billing'),false);assert.equal(roles.platformAllows('support','security'),false);assert.equal(roles.platformAllows('billing','support'),false);assert.equal(roles.platformAllows('administrator','security'),true)});
const domains=load('lib/domainInspection.ts');
test('private, reserved, mapped, loopback and documentation IPs cannot be probed',()=>{for(const ip of ['127.0.0.1','10.0.0.1','192.168.1.1','169.254.169.254','100.100.100.100','172.31.1.1','0.1.2.3','198.18.1.1','203.0.113.1','::1','::ffff:127.0.0.1','fc00::1','fe80::1','2001:db8::1','2002:7f00:1::1','2001:0::1'])assert.equal(domains.isPublicAddress(ip),false,ip);assert.equal(domains.isPublicAddress('8.8.8.8'),true);assert.equal(domains.isPublicAddress('2606:4700:4700::1111'),true)});
test('only public hostname syntax is accepted, never ports or URLs',()=>{for(const name of ['localhost','service.railway.internal','https://example.com','foo.com:8443','127.0.0.1','foo.test','user@domain.com','a..com'])assert.equal(domains.normalizePublicHostname(name),null,name);assert.equal(domains.normalizePublicHostname('PARTYRENTALCRM.COM.'),'partyrentalcrm.com')});
test('private DNS answer blocks TLS connection',async()=>{let calls=0;const inspector=load('lib/domainInspection.ts',{'node:dns/promises':{lookup:async()=>[{address:'127.0.0.1',family:4}]},'node:tls':{connect:()=>{calls++;throw Error('Forbidden')},checkServerIdentity(){}}});assert.equal((await inspector.inspectDomain('private.domain.com')).state,'blocked');assert.equal(calls,0)});
test('webhook routing accepts subscriptions but not unrelated object identifiers',()=>{const ledger=load('lib/platformBillingLedger.ts',{'@/lib/prisma':{prisma:{}},'@/lib/stripe':{stripe:{}}});assert.equal(ledger.subscriptionIdFromEvent({type:'invoice.paid',data:{object:{subscription:'sub_real'}}}),'sub_real');assert.equal(ledger.subscriptionIdFromEvent({type:'invoice.paid',data:{object:{subscription:'https://evil.test'}}}),null)});
test('invalid signed webhook cannot reach reconciliation',async()=>{let calls=0;process.env.STRIPE_PLATFORM_WEBHOOK_SECRET='fixture';const api=load('app/api/webhooks/stripe-platform/route.ts',{'next/server':{NextResponse:{json:(b,o)=>new Response(JSON.stringify(b),o)}},'@/lib/stripe':{stripe:{webhooks:{constructEvent(){throw Error('invalid')}}}},'@/lib/platformBillingLedger':{acceptBillingEvent:async()=>{calls++}}});const response=await api.POST(new Request('http://localhost/api/webhooks/stripe-platform',{method:'POST',headers:{'stripe-signature':'wrong'},body:'{}'}));assert.equal(response.status,400);assert.equal(calls,0)});
test('retired development utilities expose no writes or database access',async()=>{for(const [name,methods] of Object.entries({'sync-schema':['POST'],'unblock-billing':['POST'],'login-throttle-debug':['GET','DELETE'],'setup':['POST']})){const api=load(`app/api/admin/${name}/route.ts`,{'next/server':{NextResponse:{json:(b,o)=>new Response(JSON.stringify(b),o)}}});for(const method of methods)assert.equal((await api[method]()).status,410)}});
