"use client";
import { useState } from "react";
type Inspection={checkedAt:string;localStatus:string;subscription:{id:string;status:string;liveMode:boolean;cancelAtPeriodEnd:boolean;currentPeriodEnd:number;discountApplied:boolean;prices:Array<{id:string;lookupKey:string|null;currency:string;unitAmount:number|null;interval:string|null;intervalCount:number|null;usageType:string|null;quantity:number|null;billingScheme:string}>};invoices:Array<{id:string;number:string|null;created:number;status:string|null;currency:string;amountPaid:number;amountRemaining:number;attemptCount:number}>;moreInvoices:boolean};
function amount(value:number,currency:string){return currency.toLowerCase()==="usd"?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value/100):`${value} ${currency.toUpperCase()} minor units`;}
export default function BillingInspector({organizationId}:{organizationId:string}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const [data,setData]=useState<Inspection|null>(null);
  async function inspect(){
    setBusy(true);setError("");setData(null);
    try {
      const r=await fetch(`/api/admin/organizations/${encodeURIComponent(organizationId)}/billing`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}",cache:"no-store"});
      const value=await r.json().catch(()=>null);
      if(!r.ok || !value?.subscription)throw new Error(value?.error || "Could not inspect billing. Refresh and sign in again.");
      setData(value);
    } catch(e){setError(e instanceof Error?e.message:"Billing inspection failed.");} finally {setBusy(false);}
  }
  return <section className="space-y-5"><button disabled={busy} onClick={inspect} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Reading Stripe…":"Read subscription & invoices from Stripe"}</button>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{data&&<div aria-live="polite" className="space-y-5"><div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">{data.subscription.status} · {data.subscription.liveMode?"Live mode":"TEST MODE — not live revenue"}</h2><p className="mt-2 text-sm text-slate-600">Read {new Date(data.checkedAt).toLocaleString()} · {data.subscription.id}</p><p className="mt-2 text-sm">Current period ends {new Date(data.subscription.currentPeriodEnd*1000).toLocaleString()}. {data.subscription.cancelAtPeriodEnd?"Cancellation is scheduled at period end.":"No period-end cancellation reported."}</p>{data.localStatus!==data.subscription.status&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Local status is {data.localStatus}, while Stripe reports {data.subscription.status}. Investigate webhook synchronization; this check did not overwrite either record.</p>}<p className="mt-3 text-sm text-slate-600">{data.subscription.discountApplied?"A subscription discount is present. Price lines below are before discounts.":"Price lines are before discounts, adjustments, usage and separately billed taxes."}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.subscription.prices.map(p=><div key={p.id} className="rounded-xl bg-slate-50 p-4"><p className="break-all text-sm font-semibold">{p.lookupKey||p.id}</p><p className="mt-2 text-sm">{p.unitAmount===null?"Variable or tiered amount":amount(p.unitAmount,p.currency)} / {p.intervalCount||"?"} {p.interval||"unknown interval"}</p><p className="mt-1 text-xs text-slate-600">Quantity {p.quantity??"not reported"} · {p.usageType||p.billingScheme}</p></div>)}</div></div><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Latest subscription invoices</h2><p className="mt-1 text-sm text-slate-500">Up to 12 invoices for this subscription only; not lifetime totals. {data.moreInvoices?"More invoices exist in Stripe.":"No additional invoices reported."}</p><div className="mt-4 space-y-3">{data.invoices.length?data.invoices.map(i=><article key={i.id} className="grid gap-2 rounded-xl border p-4 sm:grid-cols-3"><div><p className="break-all text-sm font-bold">{i.number||i.id}</p><p className="mt-1 text-xs text-slate-500">{new Date(i.created*1000).toLocaleDateString()} · {i.status||"unknown"}</p></div><p className="text-sm">Paid: {amount(i.amountPaid,i.currency)}<br/>Remaining: {amount(i.amountRemaining,i.currency)}</p><p className="text-sm text-slate-600">{i.attemptCount} payment attempts</p></article>):<p className="text-sm text-slate-500">Stripe returned no invoices for this subscription.</p>}</div></section></div>}</section>;
}
