import Link from "next/link";
import { requireCurrentOrganization } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import Icon from "../components/Icon";
import {PageHeading,EmptyState} from "../components/TenantUI";
export default async function CustomersPage({searchParams}:{searchParams:{q?:string;from?:string;to?:string;page?:string}}){
 const org=await requireCurrentOrganization(),q=searchParams.q?.trim().slice(0,200)||"",from=searchParams.from?.trim()||"",to=searchParams.to?.trim()||"";
 const dateFilter:{gte?:Date;lte?:Date}={};
 if(from&&!isNaN(+new Date(from)))dateFilter.gte=new Date(from);
 if(to&&!isNaN(+new Date(to)))dateFilter.lte=new Date(new Date(to).setUTCHours(23,59,59,999));
 const where={organizationId:org.id,...Object.keys(dateFilter).length?{createdAt:dateFilter}:{},...q?{AND:q.split(/\s+/).slice(0,8).map(word=>({OR:[{firstName:{contains:word,mode:"insensitive" as const}},{lastName:{contains:word,mode:"insensitive" as const}},{email:{contains:word,mode:"insensitive" as const}},{phone:{contains:word,mode:"insensitive" as const}}]}))}:{}};
 const total=await prisma.customer.count({where}),pages=Math.max(1,Math.ceil(total/25)),page=Math.min(pages,Math.max(1,Math.floor(Number(searchParams.page)||1)));
 const customers=await prisma.customer.findMany({where,orderBy:[{createdAt:"desc"},{id:"asc"}],include:{_count:{select:{orders:true}}},take:25,skip:(page-1)*25});
 const filters=new URLSearchParams({...q?{q}:{},...from?{from}:{},...to?{to}:{}});
 const pageUrl=(page:number)=>"/dashboard/customers?"+new URLSearchParams({...Object.fromEntries(filters),page:String(page)});
 return <div className="space-y-6"><PageHeading eyebrow="Relationships" title="Customers" description="Your people, their events, and every conversation in one place." actions={<><a href={"/api/customers/export?"+filters} className="tenant-button">Export CSV</a><Link href="/dashboard/customers/new" className="tenant-button tenant-button-primary"><Icon name="plus" className="h-4 w-4"/>Add customer</Link></>}/>
 <section className="tenant-panel"><div className="border-b border-slate-100 p-5"><form method="get" className="flex flex-wrap items-end gap-3"><label className="min-w-[160px] flex-1"><span className="mb-2 block text-xs font-medium text-slate-500">Find a customer</span><div className="relative"><Icon name="search" className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400"/><input name="q" defaultValue={q} placeholder="Name, email, or phone" className="w-full !pl-9"/></div></label><label><span className="mb-2 block text-xs font-medium text-slate-500">Added from</span><input type="date" name="from" defaultValue={from}/></label><label><span className="mb-2 block text-xs font-medium text-slate-500">Added through</span><input type="date" name="to" defaultValue={to}/></label><button className="tenant-button" type="submit">Apply filters</button>{filters.size>0&&<Link href="/dashboard/customers" className="tenant-button">Clear</Link>}</form></div>
 <div className="flex items-center justify-between px-5 py-4"><h2 className="text-sm font-semibold text-slate-800">Customer directory</h2><span className="text-xs text-slate-500">{total} {total===1?"customer":"customers"}{filters.size>0?" found":""}</span></div>
 {!customers.length?<EmptyState icon="users" title={filters.size?"No matching customers":"Build relationships that bring people back"} description={filters.size?"Try a different name or date range.":"Add your first customer or create an order. Their contact details and booking history will live here."} href={filters.size?"/dashboard/customers":"/dashboard/customers/new"} label={filters.size?"Clear filters":"Add a customer"}/>:<>
 <div className="hidden overflow-x-auto md:block"><table className="tenant-table"><thead><tr><th>Customer</th><th>Contact</th><th>Orders</th><th>Added</th><th><span className="sr-only">Open customer</span></th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><Link href={"/dashboard/customers/"+c.id} className="flex items-center gap-3 hover:text-emerald-700"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#edf2ef] text-xs font-semibold text-[#547269]">{c.firstName[0]}{c.lastName[0]}</span><span>{c.firstName} {c.lastName}</span></Link></td><td><a href={"mailto:"+c.email} className="hover:text-emerald-700">{c.email}</a><p className="mt-1 text-xs text-slate-400">{c.phone?<a href={"tel:"+c.phone}>{c.phone}</a>:"No phone added"}</p></td><td><span className="rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium">{c._count.orders}</span></td><td>{c.createdAt.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:org.timezone||"UTC"})}</td><td><Link href={"/dashboard/customers/"+c.id} aria-label={"Open "+c.firstName+" "+c.lastName}><Icon name="arrow" className="h-4 w-4"/></Link></td></tr>)}</tbody></table></div>
 <div className="divide-y divide-slate-100 md:hidden">{customers.map(c=><div key={c.id} className="p-5"><Link href={"/dashboard/customers/"+c.id} className="flex items-center justify-between gap-3"><span className="text-base font-semibold text-slate-900">{c.firstName} {c.lastName}</span><Icon name="arrow" className="h-4 w-4 text-emerald-700"/></Link><a href={"mailto:"+c.email} className="mt-2 block break-all text-sm text-slate-500">{c.email}</a><div className="mt-3 flex items-center justify-between text-xs text-slate-500">{c.phone?<a className="py-2" href={"tel:"+c.phone}>{c.phone}</a>:<span>No phone added</span>}<span className="rounded-lg bg-slate-100 px-2 py-1">{c._count.orders} orders</span></div></div>)}</div>
 <div className="flex items-center justify-between gap-3 border-t border-slate-100 px-5 py-4"><span className="text-xs text-slate-500">{(page-1)*25+1}–{Math.min(page*25,total)} of {total}</span><nav className="flex items-center gap-3" aria-label="Customer pages">{page>1&&<Link href={pageUrl(page-1)} className="tenant-button">Previous</Link>}<span className="text-xs text-slate-500">Page {page} of {pages}</span>{page<pages&&<Link href={pageUrl(page+1)} className="tenant-button">Next</Link>}</nav></div></>}
 </section></div>;
}
