import Link from "next/link";
import {getPlan,TRIAL_DAYS} from "@/lib/plans";
import Icon,{type IconName} from "@/app/dashboard/components/Icon";
import ProductTour from "./ProductTour";
import "./marketing-home.css";
const workflows:{icon:IconName;title:string;body:string;link:string}[]=[
 {icon:"orders",title:"Keep every booking together",body:"Quotes, customer details, rental items, payments, and agreements in one order workspace.",link:"/features"},
 {icon:"box",title:"Know what you can rent out",body:"Manage your catalog and item condition. Check quantities against the event dates before accepting a reservation.",link:"/resources/online-booking-availability"},
 {icon:"truck",title:"Make delivery day easier to follow",body:"Connect the office, warehouse, and drivers with assignments, pull lists, and delivery tools.",link:"/resources/driver-dispatch-planning"},
 {icon:"globe",title:"Put your rental business online",body:"Build a customer storefront connected to your catalog, with your branding and an online booking flow.",link:"/features"},
];
export const HOME_FAQS=[
 ["Is this for a business like mine?","Party Rental CRM is built for party and event rental companies—tents, tables, chairs, inflatables, linens, and other event equipment. Start with your own catalog and configure your prices and rental policies."],
 ["Can I see the software before creating an account?","Yes. The one-minute animated tour on this page shows the workflow with fictional bookings. Play, pause, or jump to any chapter. Your free trial lets you explore the working account with your own inventory."],
 ["Do I need a credit card for the trial?",`No. Create your business account and explore the workspace for ${TRIAL_DAYS} days without entering payment card details.`],
 ["What happens after the trial?","Contact us to activate the paid plan that fits your business. Platform subscriptions currently require manual activation; your trial does not automatically charge a card."],
 ["Can I bring my current inventory?","You can add items yourself, start from the built-in rental catalog, or use the inventory CSV import. Review imported quantities, prices, and photos before publishing them."],
 ["What do I need before accepting online bookings?","Add inventory and prices, review your rental policies, and publish your storefront. Connect and configure payment processing before taking online card payments. Payment processor fees may apply."],
];
export default function MarketingHomePage(){const starter=getPlan("starter"),growth=getPlan("growth");return <div className="crm-marketing">
 <section className="crm-hero"><div className="crm-hero-grid" aria-hidden="true"/><div className="crm-wrap relative"><div className="crm-hero-copy"><span className="crm-eyebrow"><span/>SOFTWARE FOR PARTY & EVENT RENTALS</span><h1>Run a smoother<br/><em>rental weekend.</em></h1><p>Bookings, inventory, customers, and delivery plans.<br className="hidden sm:block"/> One clear workspace for the business behind the celebration.</p><div className="crm-hero-actions"><Link href="/signup" className="crm-cta">Start your free trial<Icon name="arrow" className="h-4 w-4"/></Link><a href="#product-tour" className="crm-cta crm-cta-light"><span className="crm-play-icon">▶</span>Watch the 1-minute tour</a></div><div className="crm-reassurance"><span><Icon name="check"/>{TRIAL_DAYS} days free</span><span><Icon name="check"/>No credit card</span><span><Icon name="check"/>Plans from ${starter.monthlyPrice}/mo</span></div></div><div className="crm-tour-intro"><span>TAKE A LOOK INSIDE</span><p>A rental business, from the first booking to a packed truck.</p></div><ProductTour/><div className="crm-rental-types"><span>BUILT AROUND WHAT YOU RENT</span><p>Tents & canopies <i/> Tables & chairs <i/> Inflatables <i/> Wedding & event equipment</p></div></div></section>
 <section className="crm-section"><div className="crm-wrap"><div className="crm-section-heading"><div><p className="crm-eyebrow">LESS CHASING. MORE CLARITY.</p><h2>The booking is just<br/>the beginning.</h2></div><p>A successful event needs more than a reservation. Keep the details your office and crew need connected from the start.</p></div><div className="crm-workflow-grid">{workflows.map((w,i)=><Link key={w.title} href={w.link} className="crm-workflow-card"><div className="crm-workflow-top"><span className="crm-feature-icon"><Icon name={w.icon}/></span><span>0{i+1}</span></div><h3>{w.title}</h3><p>{w.body}</p><span className="crm-text-link">Explore the tools<Icon name="arrow"/></span></Link>)}</div></div></section>
 <section className="crm-day-section"><div className="crm-wrap crm-day-grid"><div><p className="crm-eyebrow">BUILT FOR THE WORK BETWEEN EVENTS</p><h2>One place to answer<br/>“Are we ready?”</h2><p className="crm-body-copy">The order, the payment, the equipment, and the crew should tell the same story. Give everyone a clearer starting point for a busy weekend.</p><Link href="/demo" className="crm-cta crm-cta-light">Explore the product tour<Icon name="arrow" className="h-4 w-4"/></Link></div><div className="crm-day-checklist">{[{n:"01",time:"In the office",title:"Which bookings need attention?",body:"Find open quotes, pending orders, and balances to collect.",icon:"orders"},{n:"02",time:"In the warehouse",title:"What needs to go on the truck?",body:"Open the order's rental items and packing workflow.",icon:"box"},{n:"03",time:"On delivery day",title:"Who is handling this event?",body:"See driver assignments and keep event details close at hand.",icon:"truck"}].map(row=><div key={row.n}><span className="crm-day-number">{row.n}</span><div><small>{row.time}</small><h3>{row.title}</h3><p>{row.body}</p></div><Icon name={row.icon as IconName}/></div>)}</div></div></section>
 <section className="crm-section"><div className="crm-wrap"><div className="crm-center-heading"><p className="crm-eyebrow">A CLEAR FIRST STEP</p><h2>Start with your business.<br/>Build at your pace.</h2><p>You do not need your whole catalog ready to explore the workspace.</p></div><div className="crm-setup-grid">{[["Create your account","Add your business name and owner login. Your trial starts with a private workspace."],["Add your first rentals","Set quantities and prices. Use the built-in catalog or import a CSV to get a head start."],["Get ready for bookings","Review your website, policies, and payment setup. Publish when you are ready."]].map(([title,body],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
 <section className="crm-pricing-section"><div className="crm-wrap crm-pricing-grid"><div><p className="crm-eyebrow">ROOM TO GROW</p><h2>A plan for your<br/>next chapter.</h2><p className="crm-body-copy">Begin with the essentials. Compare team limits and operations features before choosing a paid plan.</p><Link href="/pricing" className="crm-text-link">Compare every plan<Icon name="arrow"/></Link></div><div className="crm-price-card"><div><span>STARTER</span><p>Get your rental business organized.</p></div><p className="crm-price"><b>${starter.monthlyPrice}</b><span>/ month</span></p><ul>{["Rental website & online booking","Inventory, orders & customers","Quotes, agreements & payment tracking",`${starter.limits.officeUsers} office user · ${starter.limits.crewUsers} crew logins`].map(line=><li key={line}><Icon name="check"/>{line}</li>)}</ul><Link href="/signup" className="crm-cta">Try it free for {TRIAL_DAYS} days<Icon name="arrow" className="h-4 w-4"/></Link><small>No card required. Paid plans activated with our team.</small></div><div className="crm-price-card crm-price-growth"><div><span>GROWTH</span><p>For a team and a busier schedule.</p></div><p className="crm-price"><b>${growth.monthlyPrice}</b><span>/ month</span></p><ul>{["Everything in Starter","Driver dispatch & route management","Warehouse & packing workflow",`${growth.limits.officeUsers} office users · ${growth.limits.crewUsers} crew logins`].map(line=><li key={line}><Icon name="check"/>{line}</li>)}</ul><Link href="/pricing" className="crm-cta crm-cta-light">See plan details<Icon name="arrow" className="h-4 w-4"/></Link><small>See the full comparison for plan inclusions.</small></div></div></section>
 <section className="crm-section"><div className="crm-wrap crm-faq-grid"><div><p className="crm-eyebrow">BEFORE YOU START</p><h2>A few things<br/>worth knowing.</h2><p className="crm-body-copy">Have a question about your rental business?</p><Link href="/contact" className="crm-text-link">Get in touch<Icon name="arrow"/></Link></div><div>{HOME_FAQS.map(([question,answer])=><details key={question} className="crm-faq"><summary>{question}<Icon name="plus"/></summary><p>{answer}</p></details>)}</div></div></section>
 <section className="crm-final"><div className="crm-wrap"><span className="crm-eyebrow">YOUR BUSINESS. A CLEARER PICTURE.</span><h2>Make room for<br/>a better way to work.</h2><p>Bring your next booking, your rental inventory,<br className="hidden sm:block"/> and your team into one workspace.</p><Link href="/signup" className="crm-cta">Start your free trial<Icon name="arrow" className="h-4 w-4"/></Link><small>{TRIAL_DAYS} days free · No credit card required</small></div></section>
 </div>}
