"use client";

import { useEffect, useState } from "react";

const views = ["Command Center", "Orders", "Inventory", "Dispatch", "Storefront"] as const;
type View = (typeof views)[number];

const activity = [
  ["New booking", "Johnson Wedding · Sep 19", "+$1,284"],
  ["Payment received", "Order #1039 · paid in full", "+$642"],
  ["Route optimized", "Friday · 6 delivery stops", "18 mi saved"],
  ["Inventory protected", "20×40 Frame Tent reserved", "Synced"],
];

function Shell({ children, active }: { children: React.ReactNode; active: View }) {
  return <div className="grid min-h-[500px] grid-cols-1 bg-[#f5f7fb] md:grid-cols-[188px_1fr]">
    <aside className="hidden border-r border-slate-800 bg-[#08111f] p-4 text-white md:block">
      <div className="mb-7 flex items-center gap-2 px-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 text-xs font-black shadow-lg shadow-blue-950/30">PR</div><div><div className="text-xs font-black">PartyRentalCRM</div><div className="text-[9px] text-slate-400">Rental OS</div></div></div>
      {views.map((x)=><div key={x} className={`mb-1.5 rounded-xl px-3 py-2.5 text-xs font-semibold transition ${active===x?'bg-blue-600 text-white shadow-lg shadow-blue-950/20':'text-slate-400'}`}>{x}</div>)}
      <div className="mt-8 rounded-xl border border-slate-700 bg-slate-900 p-3"><div className="flex items-center gap-2 text-[10px] font-bold text-emerald-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>All systems live</div><div className="mt-2 text-[9px] leading-4 text-slate-500">Bookings, inventory and fulfillment are synced.</div></div>
    </aside>{children}</div>;
}

function CommandCenter({ tick }: { tick: number }) {
  return <div className="p-4 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-blue-600">Tuesday · September 16</div><h3 className="mt-1 text-xl font-black tracking-tight text-slate-950 sm:text-2xl">Good afternoon. Your weekend is taking shape.</h3></div><button className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-blue-600/20">+ New order</button></div>
    <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Weekend revenue","$12,840","+$2,460 today"],["Events","18","7 need prep"],["Open balances","$4,286","5 customers"],["Fleet","6 stops","Routes ready"]].map(([a,b,c],i)=><div key={a} className={`rounded-2xl border bg-white p-4 shadow-sm transition-all duration-500 ${tick%4===i?'border-blue-300 shadow-blue-100':'border-slate-200'}`}><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{a}</div><div className="mt-1 text-xl font-black text-slate-950">{b}</div><div className={`mt-1 text-[9px] font-bold ${i===0?'text-emerald-600':'text-slate-500'}`}>{c}</div></div>)}</div>
    <div className="mt-3 grid gap-3 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-xs font-black">Upcoming fulfillment</div><div className="text-[9px] text-slate-400">What your team needs to move next</div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-black text-emerald-600">LIVE</span></div><div className="mt-3 space-y-2">{[["#1048","Johnson Wedding","Fri · 9:00 AM","READY","$1,284"],["#1049","Syracuse University","Fri · 1:00 PM","PREP","$860"],["#1052","Martinez Graduation","Sat · 8:00 AM","BALANCE","$1,540"]].map((r,i)=><div key={r[0]} className={`grid grid-cols-[48px_1fr_auto] items-center gap-2 rounded-xl border p-2.5 text-[9px] transition ${tick%3===i?'border-blue-200 bg-blue-50/50':'border-slate-100'}`}><b className="text-blue-600">{r[0]}</b><div><b className="text-slate-800">{r[1]}</b><div className="text-slate-400">{r[2]}</div></div><div className="text-right"><b>{r[4]}</b><div className={i===0?'text-emerald-600':'text-amber-600'}>{r[3]}</div></div></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-black">Live activity</div><div className="mt-3 space-y-2">{activity.map((r,i)=><div key={r[0]} className={`rounded-xl p-2.5 transition-all duration-500 ${tick%activity.length===i?'scale-[1.02] bg-blue-50 ring-1 ring-blue-200':'bg-slate-50'}`}><div className="flex justify-between gap-2 text-[9px]"><b>{r[0]}</b><b className="text-blue-600">{r[2]}</b></div><div className="mt-1 text-[8px] text-slate-400">{r[1]}</div></div>)}</div></div></div></div>;
}

function Orders() { return <div className="p-4 sm:p-6"><div className="flex items-end justify-between"><div><div className="text-[10px] font-black uppercase tracking-wider text-blue-600">Orders workspace</div><h3 className="mt-1 text-2xl font-black">18 events · $12,840 booked</h3></div><button className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold text-white">Create order</button></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-[70px_1.3fr_1fr_.8fr_.7fr] gap-3 border-b bg-slate-50 px-4 py-3 text-[9px] font-black uppercase text-slate-400"><span>Order</span><span>Customer / event</span><span>Schedule</span><span>Status</span><span>Total</span></div>{[["#1048","Johnson Wedding","Sep 19 · 9 AM","Ready","$1,284"],["#1049","Syracuse University","Sep 19 · 1 PM","Prep","$860"],["#1050","Miller Birthday","Sep 19 · 3 PM","Paid","$495"],["#1052","Martinez Graduation","Sep 20 · 8 AM","Balance due","$1,540"],["#1054","Rivera Reception","Sep 20 · 11 AM","Confirmed","$2,320"]].map((r,i)=><div key={r[0]} className={`grid grid-cols-[70px_1.3fr_1fr_.8fr_.7fr] items-center gap-3 border-b border-slate-100 px-4 py-3 text-[10px] ${i===1?'bg-blue-50/60':''}`}><b className="text-blue-600">{r[0]}</b><b>{r[1]}</b><span className="text-slate-500">{r[2]}</span><span className="w-fit rounded-full bg-slate-100 px-2 py-1 font-bold">{r[3]}</span><b>{r[4]}</b></div>)}</div><div className="mt-3 grid grid-cols-3 gap-3">{[["Deposits collected","$8,554"],["Balance outstanding","$4,286"],["Avg. order","$713"]].map(x=><div key={x[0]} className="rounded-xl border border-slate-200 bg-white p-3"><div className="text-[9px] text-slate-400">{x[0]}</div><b className="text-lg">{x[1]}</b></div>)}</div></div> }

function Inventory() { return <div className="p-4 sm:p-6"><div className="text-[10px] font-black uppercase tracking-wider text-blue-600">Availability engine</div><h3 className="mt-1 text-2xl font-black">Know what is safe to sell.</h3><div className="mt-5 grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between text-xs"><b>Weekend inventory pressure</b><span className="text-slate-400">Sep 18–20</span></div><div className="mt-4 space-y-4">{[["20×40 Frame Tent",4,4],["White Resin Chairs",160,200],["60in Round Tables",24,30],["Bistro Lights",8,12]].map(([n,u,t])=><div key={String(n)}><div className="flex justify-between text-[10px]"><b>{n}</b><span>{u}/{t} reserved</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${u===t?'bg-rose-500':'bg-blue-600'}`} style={{width:`${Number(u)/Number(t)*100}%`}}/></div></div>)}</div></div><div className="space-y-3"><div className="rounded-2xl bg-rose-50 p-4 ring-1 ring-rose-100"><div className="text-[9px] font-black uppercase text-rose-600">Conflict prevented</div><div className="mt-1 text-sm font-black">20×40 Frame Tent</div><p className="mt-2 text-[9px] leading-4 text-rose-700">All 4 are committed Saturday. New booking is blocked before checkout.</p></div><div className="rounded-2xl bg-emerald-50 p-4 ring-1 ring-emerald-100"><div className="text-[9px] font-black uppercase text-emerald-600">Available</div><div className="mt-1 text-sm font-black">40 White Resin Chairs</div><p className="mt-2 text-[9px] leading-4 text-emerald-700">Safe quantity remaining after current reservations.</p></div></div></div></div> }

function Dispatch() { return <div className="p-4 sm:p-6"><div className="text-[10px] font-black uppercase tracking-wider text-blue-600">Dispatch board</div><h3 className="mt-1 text-2xl font-black">Friday route · 6 stops</h3><div className="mt-5 grid gap-3 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-2">{[["8:00","Warehouse","Load complete"],["9:00","Johnson Wedding","12 min away"],["11:30","Miller Birthday","On route"],["1:00","Syracuse University","Scheduled"],["3:00","Rivera Reception","Scheduled"]].map((r,i)=><div key={r[0]} className={`flex gap-3 rounded-xl border p-3 ${i===1?'border-blue-200 bg-blue-50':'border-slate-200 bg-white'}`}><b className="text-[10px] text-blue-600">{r[0]}</b><div><b className="text-[10px]">{r[1]}</b><div className="text-[9px] text-slate-400">{r[2]}</div></div></div>)}</div><div className="relative min-h-[300px] overflow-hidden rounded-2xl border border-slate-200 bg-[linear-gradient(45deg,#eef2f7_25%,transparent_25%),linear-gradient(-45deg,#eef2f7_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#eef2f7_75%),linear-gradient(-45deg,transparent_75%,#eef2f7_75%)] bg-[size:28px_28px] bg-[position:0_0,0_14px,14px_-14px,-14px_0px]"><svg className="absolute inset-0 h-full w-full" viewBox="0 0 500 300"><path d="M45 245 C120 170 150 235 210 150 S330 70 455 55" fill="none" stroke="#2563eb" strokeWidth="5" strokeDasharray="8 8"/><g fill="#2563eb">{[[45,245],[150,200],[210,150],[330,85],[455,55]].map(([x,y])=><circle key={`${x}-${y}`} cx={x} cy={y} r="9"/>)}</g></svg><div className="absolute bottom-4 left-4 rounded-xl bg-white p-3 shadow-lg"><div className="text-[9px] text-slate-400">Route optimization</div><b className="text-xs">18 miles saved · 42 min faster</b></div></div></div></div> }

function Storefront() { return <div className="p-4 sm:p-6"><div className="text-[10px] font-black uppercase tracking-wider text-blue-600">Customer storefront</div><h3 className="mt-1 text-2xl font-black">Bookings start before your office opens.</h3><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="rounded-xl bg-slate-950 px-4 py-3 text-white"><div className="flex justify-between"><b className="text-xs">Your Party Rental Co.</b><span className="rounded-lg bg-blue-600 px-3 py-1 text-[9px] font-bold">Check availability</span></div></div><div className="p-4"><div className="rounded-2xl bg-gradient-to-r from-blue-50 to-indigo-50 p-5 text-center"><div className="text-lg font-black">Everything you need for the perfect event.</div><div className="mt-2 text-[9px] text-slate-500">Choose rentals · Pick your date · Reserve online</div></div><div className="mt-4 grid grid-cols-3 gap-3">{[["Tents","From $250"],["Tables & Chairs","From $2.50"],["Inflatables","From $199"]].map(x=><div key={x[0]} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="mb-6 h-14 rounded-lg bg-gradient-to-br from-slate-200 to-slate-100"/><b className="text-[10px]">{x[0]}</b><div className="text-[9px] text-blue-600">{x[1]}</div></div>)}</div></div></div></div> }

export default function MarketingProductDemo() {
  const [view, setView] = useState<View>("Command Center"); const [tick,setTick]=useState(0);
  useEffect(()=>{const id=window.setInterval(()=>setTick(v=>v+1),2200);return()=>window.clearInterval(id)},[]);
  useEffect(()=>{const id=window.setInterval(()=>setView(v=>views[(views.indexOf(v)+1)%views.length]),6500);return()=>window.clearInterval(id)},[]);
  const body=view==="Command Center"?<CommandCenter tick={tick}/>:view==="Orders"?<Orders/>:view==="Inventory"?<Inventory/>:view==="Dispatch"?<Dispatch/>:<Storefront/>;
  return <div className="overflow-hidden rounded-[28px] border border-slate-200 bg-white text-left shadow-[0_50px_120px_-45px_rgba(15,23,42,.6)]"><div className="flex items-center gap-3 border-b border-slate-200 bg-white px-4 py-3"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-rose-300"/><span className="h-2.5 w-2.5 rounded-full bg-amber-300"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-300"/></div><div className="mx-auto flex gap-1 rounded-xl bg-slate-100 p-1">{views.map(x=><button key={x} onClick={()=>setView(x)} className={`hidden rounded-lg px-2.5 py-1 text-[9px] font-bold transition sm:block ${view===x?'bg-white text-blue-600 shadow-sm':'text-slate-400'}`}>{x}</button>)}</div><span className="flex items-center gap-1 text-[9px] font-black text-emerald-600"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/>LIVE</span></div><div key={view} className="animate-[fadeIn_.35s_ease-out]"><Shell active={view}>{body}</Shell></div></div>;
}
