import Link from "next/link";
import MarketingProductDemo from "./MarketingProductDemo";

const outcomes = [
  ["Get online", "A professional rental storefront without building a separate website first."],
  ["Take bookings", "Customers browse, choose dates, sign and pay while you are delivering or setting up."],
  ["Protect inventory", "Know what is already promised before you tell the next customer yes."],
  ["Get paid", "Keep deposits, balances and payment status attached to the actual order."],
  ["Run delivery day", "Turn bookings into a schedule your office, warehouse and drivers can follow."],
  ["Look professional", "Quotes, contracts, customer records and order details live in one system."],
];

const launch = [
  ["1", "Name your business", "Add your company details, logo, service area and policies."],
  ["2", "Add what you rent", "Start with tents, tables, chairs, inflatables, linens or whatever you own."],
  ["3", "Publish your storefront", "Your catalog, pricing and booking flow are ready for customers."],
  ["4", "Share your link", "Put it on Google, Facebook, Instagram, texts and business cards."],
  ["5", "Take the booking", "The customer chooses a date, reserves equipment and pays online."],
];

export default function MarketingHomePage() {
  return <div className="overflow-hidden bg-white text-slate-950">
    <section className="relative border-b border-slate-200 bg-[linear-gradient(180deg,#f7fbff_0%,#ffffff_78%)]">
      <div className="absolute inset-x-0 top-0 -z-0 h-[520px] bg-[radial-gradient(circle_at_50%_-10%,rgba(37,99,235,.16),transparent_52%)]"/>
      <div className="relative mx-auto max-w-7xl px-5 pb-20 pt-16 sm:px-6 sm:pb-28 sm:pt-24 lg:px-8">
        <div className="mx-auto max-w-4xl text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-4 py-2 text-xs font-black uppercase tracking-[.15em] text-blue-700"><span className="h-2 w-2 rounded-full bg-emerald-500"/>Built for party rental owners</div>
          <h1 className="mx-auto mt-7 max-w-4xl text-balance text-5xl font-black leading-[.98] tracking-[-.055em] text-slate-950 sm:text-7xl">Start your rental business with the system you&apos;ll need when it gets busy.</h1>
          <p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600 sm:text-xl">Launch a bookable website, show your inventory, take deposits, prevent double bookings and organize delivery day — without stitching together five different tools.</p>
          <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="rounded-xl bg-blue-600 px-8 py-4 font-black text-white shadow-[0_18px_50px_-18px_rgba(37,99,235,.65)] transition hover:-translate-y-0.5 hover:bg-blue-700">Start building free</Link><Link href="/demo" className="rounded-xl border border-slate-300 bg-white px-8 py-4 font-black text-slate-800 shadow-sm transition hover:border-slate-400">See the software →</Link></div>
          <div className="mt-5 flex flex-wrap justify-center gap-x-5 gap-y-2 text-sm text-slate-500"><span>14-day free trial</span><span>•</span><span>No credit card</span><span>•</span><span>Website included</span><span>•</span><span>Plans from $49/mo</span></div>
        </div>
        <div className="relative mx-auto mt-14 max-w-6xl"><div className="absolute -inset-10 -z-0 rounded-[3rem] bg-blue-100/60 blur-3xl"/><div className="relative"><MarketingProductDemo/></div></div>
      </div>
    </section>

    <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-6 lg:px-8"><p className="text-center text-xs font-black uppercase tracking-[.2em] text-slate-400">The first questions a new rental owner needs answered</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Can customers book me online?","Yes — storefront + checkout."],["Will I double-book equipment?","Availability checks every event date."],["How do I collect deposits?","Payments stay tied to the order."],["How do I know what goes out?","Bookings become fulfillment work."]].map(([q,a])=><div key={q} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-sm font-black">{q}</div><div className="mt-2 text-sm leading-6 text-slate-600">{a}</div></div>)}</div></div></section>

    <section className="bg-[#f7f9fc]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">What you actually need</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-6xl">Not more software. A way to get booked and stay organized.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-600 lg:justify-self-end">When you are starting, the problem is not “enterprise operations.” It is getting a professional business online, knowing what you can promise, collecting money and making sure Saturday does not become chaos.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{outcomes.map(([t,b],i)=><div key={t} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-sm font-black text-blue-600">0{i+1}</div><h3 className="mt-6 text-xl font-black">{t}</h3><p className="mt-3 leading-7 text-slate-600">{b}</p></div>)}</div></div></section>

    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">From idea to first booking</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-6xl">You should not need a developer just to start renting.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Set up the business once. The same information powers what your customer sees and what your team uses after the order comes in.</p></div><div className="relative mt-14 grid gap-4 lg:grid-cols-5">{launch.map(([n,t,b])=><div key={n} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-600 text-sm font-black text-white">{n}</div><h3 className="mt-6 text-lg font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{b}</p></div>)}</div></div></section>

    <section className="border-y border-slate-200 bg-blue-50/60"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-6 sm:py-28 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Your website is part of the system</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-6xl">A customer should be able to go from “I need chairs” to booked.</h2><p className="mt-6 text-lg leading-8 text-slate-600">They choose the event date, browse what you actually rent, see pricing, reserve available equipment and move into payment. You receive an order instead of another “how much?” message.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-slate-700">Rental catalog</span><span className="rounded-full border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-slate-700">Date-aware availability</span><span className="rounded-full border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-slate-700">Deposits</span><span className="rounded-full border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-slate-700">Contracts</span></div></div><div className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-xl"><div className="border-b border-slate-200 px-5 py-4"><div className="text-sm font-black">Your Party Rental Co.</div><div className="text-xs text-slate-400">Customer storefront</div></div><div className="p-5"><div className="rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 p-7 text-white"><div className="text-2xl font-black">Make your event happen.</div><div className="mt-2 text-sm text-blue-100">Choose your date. Browse rentals. Reserve online.</div><div className="mt-5 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-black text-blue-700">Check my date</div></div><div className="mt-4 grid grid-cols-3 gap-3">{["Tents","Tables & Chairs","Inflatables"].map(x=><div key={x} className="rounded-xl border border-slate-200 p-3"><div className="aspect-[4/3] rounded-lg bg-slate-100"/><div className="mt-2 text-xs font-black">{x}</div></div>)}</div></div></div></div></section>

    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="rounded-[28px] border border-slate-200 bg-slate-50 p-6 sm:p-8"><div className="flex items-center justify-between"><div><div className="text-sm font-black">Saturday availability</div><div className="text-xs text-slate-400">What can I still rent?</div></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">LIVE</span></div><div className="mt-7 space-y-5">{[["20×40 Tent",1,1],["White Chairs",120,200],["6ft Tables",14,24],["Bounce House",2,3]].map(([name,used,total])=><div key={String(name)}><div className="flex justify-between text-sm"><b>{name}</b><span className="text-slate-500">{Number(total)-Number(used)} left</span></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className={`h-2 rounded-full ${used===total?'bg-rose-500':'bg-blue-600'}`} style={{width:`${Number(used)/Number(total)*100}%`}}/></div></div>)}</div><div className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-4"><div className="text-xs font-black text-rose-700">20×40 TENT FULLY RESERVED</div><div className="mt-1 text-sm text-rose-700">The storefront stops another customer from reserving it.</div></div></div><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">The mistake that gets expensive fast</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-6xl">Do not build your business around a calendar in your head.</h2><p className="mt-6 text-lg leading-8 text-slate-600">The moment two customers want the same Saturday, inventory matters. Party Rental CRM ties quantities to event dates so your storefront and your office are looking at the same availability.</p></div></div></div></section>

    <section className="bg-blue-600"><div className="mx-auto max-w-5xl px-5 py-20 text-center text-white sm:px-6 sm:py-24"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-100">Start before the first busy weekend</p><h2 className="mt-5 text-balance text-4xl font-black tracking-[-.05em] sm:text-6xl">Build the business once. Be ready when the bookings come.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-blue-100">Website, booking, inventory, customers, payments and delivery workflow in one place from day one.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="rounded-xl bg-white px-8 py-4 font-black text-blue-700 shadow-xl">Start building free</Link><Link href="/pricing" className="rounded-xl border border-blue-300 px-8 py-4 font-black text-white hover:bg-blue-700">See pricing</Link></div><p className="mt-4 text-sm text-blue-200">14 days free · No credit card required</p></div></section>
  </div>;
}
