import Link from "next/link";
import MarketingProductDemo from "./MarketingProductDemo";

const features = [
  ["🌐", "Rental website included", "Launch a professional, mobile-friendly storefront with your rentals, pricing and booking flow."],
  ["📅", "Online booking 24/7", "Customers choose event dates and start reservations while you are delivering, setting up or sleeping."],
  ["📦", "Real-time inventory", "Tie quantities to event dates so the same tent, chair or inflatable is not promised twice."],
  ["💳", "Deposits & payments", "Collect deposits and keep balances, receipts and payment status connected to each order."],
  ["🚚", "Delivery & pickup", "Turn confirmed events into delivery and pickup work your office, warehouse and drivers can follow."],
  ["👥", "Customer CRM", "Keep contact details, booking history, notes and event information together instead of scattered in texts."],
  ["✍️", "Contracts & signatures", "Keep rental agreements with the booking instead of chasing separate PDFs and emails."],
  ["📊", "Reports & analytics", "See bookings, revenue and inventory activity so you can understand what is actually growing."],
];

const launch = [
  ["1", "🏢", "Create your business", "Add your company name, service area, logo and rental policies."],
  ["2", "🎪", "Add your rentals", "Start with tents, tables, chairs, inflatables, linens, games or whatever you own."],
  ["3", "📸", "Make it look real", "Upload strong photos, prices and descriptions so customers can shop with confidence."],
  ["4", "🚀", "Publish your storefront", "Share your rental website on Google, Facebook, Instagram and your business cards."],
  ["5", "💰", "Take your first booking", "A customer chooses a date, reserves available equipment and moves into payment."],
];

const faqs = [
  ["What is party rental software?", "Party rental software helps event rental companies manage online bookings, inventory availability, customers, payments, contracts, delivery and pickup work from one connected system."],
  ["Can I use Party Rental CRM if I am just starting?", "Yes. The setup is designed to help a new rental owner create the business profile, add inventory, publish a customer storefront and start accepting bookings without building separate systems first."],
  ["Does it include a party rental website?", "Yes. Your customer-facing rental catalog and booking flow are part of the platform, so the website and the operating side of the business can use the same rental data."],
  ["Can it help prevent double bookings?", "Availability is tied to rental quantities and event dates so already-committed inventory can be surfaced before another reservation is accepted."],
];

const tentPhoto = "https://images.unsplash.com/photo-1675376616537-c8aa9ddc9977?auto=format&fit=crop&q=82&w=1600";
const eventPhoto = "https://images.unsplash.com/photo-1687362575187-ee2bfa7a7d23?auto=format&fit=crop&q=82&w=1400";

export default function MarketingHomePage() {
  return <div className="overflow-hidden bg-white text-slate-950">
    <section className="relative border-b border-slate-200 bg-[linear-gradient(180deg,#eff7ff_0%,#ffffff_82%)]">
      <div className="absolute left-[-8rem] top-24 h-72 w-72 rounded-full bg-cyan-200/35 blur-3xl"/><div className="absolute right-[-8rem] top-10 h-80 w-80 rounded-full bg-violet-200/35 blur-3xl"/>
      <div className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-14 sm:px-6 sm:pt-20 lg:grid-cols-[.92fr_1.08fr] lg:items-center lg:px-8">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white px-4 py-2 text-xs font-black uppercase tracking-[.14em] text-blue-700 shadow-sm"><span>🎉</span> Built for party & event rental owners</div>
          <h1 className="mt-7 text-balance text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-[68px]">Party rental software that helps you <span className="text-blue-600">get booked</span> and stay organized.</h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">Launch your rental website, accept online bookings, protect inventory, collect deposits and run delivery day from one place — whether you rent bounce houses, tents, tables, chairs, linens or event equipment.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="rounded-xl bg-blue-600 px-7 py-4 text-center font-black text-white shadow-[0_18px_45px_-16px_rgba(37,99,235,.65)] transition hover:-translate-y-0.5 hover:bg-blue-700">🚀 Start building free</Link><Link href="/demo" className="rounded-xl border border-slate-300 bg-white px-7 py-4 text-center font-black text-slate-800 shadow-sm hover:border-blue-300">▶ See how it works</Link></div>
          <div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-sm font-medium text-slate-500"><span>✓ 14-day free trial</span><span>✓ No credit card</span><span>✓ Website included</span><span>✓ From $49/mo</span></div>
        </div>
        <div className="relative min-h-[520px]">
          <div className="absolute left-0 top-0 h-[390px] w-[82%] overflow-hidden rounded-[32px] border-4 border-white bg-slate-100 shadow-2xl"><img src={tentPhoto} alt="White party rental wedding tent set up for an outdoor event" className="h-full w-full object-cover" loading="eager"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/75 to-transparent p-6 pt-20 text-white"><div className="text-xs font-black uppercase tracking-[.16em] text-blue-200">The business your customer sees</div><div className="mt-1 text-2xl font-black">Professional from the first booking.</div></div></div>
          <div className="absolute bottom-2 right-0 w-[62%] overflow-hidden rounded-[26px] border-4 border-white bg-white shadow-2xl"><div className="bg-slate-950 px-4 py-3 text-white"><div className="flex items-center justify-between"><b className="text-xs">Saturday · Sep 19</b><span className="rounded-full bg-emerald-400/15 px-2 py-1 text-[9px] font-black text-emerald-300">● LIVE</span></div></div><div className="space-y-3 p-4">{[["🎪","20×40 Tent","FULL"],["🪑","White Chairs","80 LEFT"],["🎈","Bounce House","1 LEFT"]].map(([e,n,s],i)=><div key={n} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="text-xl">{e}</span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{n}</b><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className={`h-full ${i===0?'w-full bg-rose-500':i===1?'w-3/5 bg-blue-500':'w-2/3 bg-amber-500'}`}/></div></div><b className={`text-[9px] ${i===0?'text-rose-600':'text-slate-500'}`}>{s}</b></div>)}</div></div>
          <div className="absolute right-4 top-8 rounded-2xl border border-emerald-200 bg-white px-4 py-3 shadow-xl"><div className="text-[10px] font-black uppercase tracking-wider text-emerald-600">💳 Payment received</div><div className="mt-1 text-xl font-black">+$642.00</div></div>
        </div>
      </div>
    </section>

    <section className="border-b border-slate-200 bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-8 gap-y-4 px-5 py-5 text-sm font-bold sm:px-6 lg:px-8"><span>🎪 Tent rentals</span><span>🏰 Bounce houses</span><span>🪑 Tables & chairs</span><span>💍 Wedding rentals</span><span>📸 Photo booths</span><span>🎉 Event equipment</span></div></section>

    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Everything connected</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-6xl">The tools a party rental business actually uses.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The strongest rental platforms sell the outcome clearly: online bookings, live inventory, payments and delivery operations working together. Party Rental CRM is built around that same real-world workflow. </p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([emoji,title,body])=><article key={title} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><div className="text-3xl transition group-hover:scale-110">{emoji}</div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article>)}</div></div></section>

    <section className="border-y border-slate-200 bg-[#f7faff]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><div className="inline-flex rounded-full bg-amber-100 px-3 py-1.5 text-xs font-black text-amber-800">⚡ FROM IDEA TO FIRST BOOKING</div><h2 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-6xl">Start simple. Look established.</h2><p className="mt-5 text-lg leading-8 text-slate-600">A new owner should not need five subscriptions and a developer. Build the customer-facing business and the back office together.</p><div className="mt-8 overflow-hidden rounded-[26px] border-4 border-white shadow-xl"><img src={eventPhoto} alt="Styled party rental event setup with decor and seating" className="h-64 w-full object-cover" loading="lazy"/></div></div><div className="grid gap-3">{launch.map(([n,e,t,b])=><div key={n} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-2xl">{e}</div><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-blue-600">Step {n}</div><h3 className="mt-1 text-lg font-black">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{b}</p></div></div>)}</div></div></div></section>

    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><div className="inline-flex rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-black text-emerald-800">💡 SEE THE SYSTEM WORK</div><h2 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-5xl">A booking should do more than put a name on a calendar.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The customer booking should reserve inventory, show what is owed and become useful work for the team that has to prepare, deliver and pick it up.</p><div className="mt-7 space-y-3 text-sm font-bold text-slate-700"><div>📅 Event date captured</div><div>📦 Inventory reserved</div><div>💳 Deposit attached</div><div>🚚 Delivery work created</div></div></div><MarketingProductDemo/></div></div></section>

    <section className="border-y border-slate-200 bg-gradient-to-br from-blue-600 to-indigo-700 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-6 lg:grid-cols-[1fr_1fr] lg:items-center lg:px-8"><div><div className="text-4xl">📈</div><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Built to help a small rental company grow without losing control.</h2><p className="mt-5 text-lg leading-8 text-blue-100">Start with a few items. Keep the same system when the catalog, customer list, staff and weekend delivery schedule get bigger.</p></div><div className="grid grid-cols-2 gap-3">{[["🌐","Website"],["🛒","Bookings"],["📦","Inventory"],["💳","Payments"],["🚚","Dispatch"],["📊","Reports"]].map(([e,t])=><div key={t} className="rounded-2xl border border-white/20 bg-white/10 p-4 backdrop-blur"><div className="text-2xl">{e}</div><div className="mt-2 font-black">{t}</div></div>)}</div></div></section>

    <section className="bg-white"><div className="mx-auto max-w-4xl px-5 py-20 sm:px-6 sm:py-24"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Party rental software FAQ</p><h2 className="mt-4 text-4xl font-black tracking-tight">Questions before you start.</h2></div><div className="mt-10 divide-y divide-slate-200 rounded-2xl border border-slate-200 px-6 sm:px-8">{faqs.map(([q,a])=><details key={q} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-black">{q}<span className="text-2xl text-blue-600 group-open:rotate-45">+</span></summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>

    <section className="bg-[#eff6ff]"><div className="mx-auto max-w-5xl px-5 py-20 text-center sm:px-6 sm:py-24"><div className="text-5xl">🎉</div><h2 className="mt-5 text-balance text-4xl font-black tracking-[-.05em] sm:text-6xl">Your next booking should make the software feel cheap.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Build your website, add your rentals and get the operating system ready before the busy weekend arrives.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="rounded-xl bg-blue-600 px-8 py-4 font-black text-white shadow-xl shadow-blue-200 hover:bg-blue-700">🚀 Start free for 14 days</Link><Link href="/pricing" className="rounded-xl border border-slate-300 bg-white px-8 py-4 font-black text-slate-800">See pricing →</Link></div><p className="mt-4 text-sm text-slate-500">No credit card required.</p></div></section>
  </div>;
}
