"use client";
import {useEffect,useRef,useState} from "react";
import Icon,{type IconName} from "@/app/dashboard/components/Icon";
import {StatusBadge} from "@/app/dashboard/components/TenantUI";
import "./product-tour.css";

export const TOUR_CHAPTERS=[
 {title:"See the day ahead",nav:"Overview",icon:"home",caption:"Start with today's bookings, upcoming events, open balances, and the tasks your team needs to finish."},
 {title:"Find any booking",nav:"Orders",icon:"orders",caption:"Search orders by customer or order number. Filter quotes, confirmed bookings, and balances due."},
 {title:"Keep the whole event together",nav:"Order detail",icon:"wallet",caption:"Rental items, payments, the customer, delivery details, and the agreement stay connected to the order."},
 {title:"Organize what you rent",nav:"Inventory",icon:"box",caption:"Manage rental quantities, prices, photos, and item condition. Check availability for an event before reserving equipment."},
 {title:"Get your crew ready",nav:"Deliveries",icon:"truck",caption:"Assign drivers, open packing lists, and plan delivery and pickup work from the same bookings. Operations tools vary by plan."},
 {title:"Give customers a place to book",nav:"Website",icon:"globe",caption:"Build your rental catalog and booking website. Add your branding, publish your pages, and connect online payments when ready."},
] as const;
const demoOrders=[{id:"ORD-1048",name:"Jordan Miller",date:"Jun 21",total:"$840.00",due:"$420.00",status:"confirmed"},{id:"ORD-1049",name:"Taylor Davis",date:"Jun 22",total:"$360.00",due:"$0.00",status:"confirmed"},{id:"ORD-1050",name:"Morgan Lee",date:"Jun 22",total:"$620.00",due:"$620.00",status:"quote"}];
function Badge({status}:{status:string}){return <StatusBadge status={status}/>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="tour-panel"><h4>{title}</h4>{children}</div>}
function Tiles({values}:{values:string[][]}){return <div className="tour-tiles">{values.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
function Overview({phase}:{phase:number}){return <><Tiles values={[["Next 7 days","3"],["Net payments · 30 days","$780"],["Balance to collect","$420"]]}/><div className="tour-two-columns"><Panel title="Today's bookings"><div className={"tour-booking "+(phase>2?"tour-highlight":"")}><span className="tour-icon"><Icon name="truck"/></span><div><b>Jordan Miller</b><small>ORD-1048 · Delivery</small></div><Badge status="confirmed"/></div><div className="tour-booking"><span className="tour-icon"><Icon name="box"/></span><div><b>Taylor Davis</b><small>ORD-1049 · Customer pickup</small></div><Badge status="confirmed"/></div></Panel><Panel title="Team tasks"><div className="tour-task"><span className={phase>5?"tour-check-done":""}>{phase>5&&<Icon name="check"/>}</span><b>Check tent tops before loading</b></div><div className="tour-task"><span/><b>Prepare Saturday's pull list</b></div></Panel></div><div className="tour-note"><Icon name="calendar"/>One place to see what your rental weekend needs.</div></>}
function Orders({phase}:{phase:number}){return <><div className="tour-search"><Icon name="search"/><span>{phase>2?"Jordan Miller":"Search orders or customers"}</span><span className="tour-key">↵</span></div><div className="tour-filter-row"><span className="selected">All orders</span><span>Quotes</span><span>Confirmed</span><span>Balance due</span></div><div className="tour-order-table"><div className="tour-table-head"><span>Customer / order</span><span>Event</span><span>Status</span><span>Total</span></div>{demoOrders.filter((_,i)=>phase>4?i===0:true).map(o=><div className={"tour-table-row "+(phase>5?"tour-highlight":"")} key={o.id}><div><b>{o.name}</b><small>{o.id}</small></div><span>{o.date}</span><Badge status={o.status}/><b>{o.total}</b></div>)}</div><div className="tour-note"><Icon name="search"/>{phase>4?"Jordan's booking is right here. Open it to see the whole event.":"Find the order without digging through emails or spreadsheets."}</div></>}
function OrderDetail({phase}:{phase:number}){return <><div className="tour-record-heading"><div><b>ORD-1048</b><small>Jordan Miller · June 21</small></div><Badge status="confirmed"/></div><Tiles values={[["Order total","$840.00"],["Paid so far","$420.00"],["Balance due","$420.00"]]}/><div className="tour-two-columns"><Panel title="Rental items">{[["20 × 30 pole tent","1","$480"],["Round tables","6","$120"],["White folding chairs","60","$150"]].map(([item,qty,total])=><div className="tour-item-line" key={item}><Icon name="box"/><b>{item}</b><span>× {qty}</span><span>{total}</span></div>)}<div className="tour-item-line"><b>Delivery & tax</b><span>$90</span></div></Panel><div className="tour-detail-side"><Panel title="Customer"><b>Jordan Miller</b><small>jordan@example.com</small></Panel><Panel title="Rental agreement"><span className={"tour-inline-status "+(phase>4?"complete":"")}>{phase>4?<><Icon name="check"/>Signed agreement</>:"Awaiting signature"}</span></Panel></div></div></>}
function Inventory({phase}:{phase:number}){return <><Tiles values={[["Rental items","3"],["Categories","2"],["Need attention","1"]]}/><div className="tour-inventory-grid">{[{name:"20 × 30 pole tent",qty:"2 in stock",price:"$480",kind:"tent",status:"available"},{name:"Round table",qty:"20 in stock",price:"$20",kind:"table",status:"available"},{name:"White folding chair",qty:"120 in stock",price:"$2.50",kind:"chair",status:"needs_repair"}].map((item,i)=><div className={"tour-inventory-card "+(phase>4&&i===2?"tour-highlight":"")} key={item.name}><div className="tour-equipment"><Equipment kind={item.kind}/></div><b>{item.name}</b><small>{item.qty} · {item.price}</small><Badge status={item.status}/></div>)}</div><div className="tour-note"><Icon name="shield"/>Review condition and quantities before the next booking.</div></>}
function Deliveries({phase}:{phase:number}){return <><div className="tour-record-heading"><div><b>Delivery day</b><small>June 21 · Event bookings</small></div><span className="tour-pill">Operations</span></div><div className="tour-two-columns"><Panel title="Driver assignments"><div className="tour-booking"><span className="tour-icon"><Icon name="truck"/></span><div><b>Jordan Miller</b><small>ORD-1048 · Delivery</small></div><span className={"tour-pill "+(phase>3?"green":"")}>{phase>3?"Alex assigned":"Unassigned"}</span></div><div className="tour-packing-link"><Icon name="orders"/>Open order packing list<Icon name="arrow"/></div></Panel><Panel title="Packing list">{[["20 × 30 pole tent","1"],["Round tables","6"],["White folding chairs","60"]].map(([name,qty],i)=><div className="tour-task" key={name}><span className={phase>5+i?"tour-check-done":""}>{phase>5+i&&<Icon name="check"/>}</span><b>{name}</b><small>× {qty}</small></div>)}</Panel></div><div className="tour-note"><Icon name="check"/>Your office and crew work from the same order details.</div></>}
function Website({phase}:{phase:number}){return <div className="tour-storefront"><div className="tour-store-nav"><b>Lakeside Event Rentals</b><span>Sample storefront</span></div><div className="tour-store-hero"><span>FOR LIFE'S GOOD GATHERINGS</span><h4>Make room for<br/>a great celebration.</h4><p>Tents, tables & chairs for your next event.</p><span className="tour-store-cta">Check availability <Icon name="arrow"/></span><Equipment kind="tent"/></div><div className="tour-store-items">{["Tents","Tables","Chairs"].map((name,i)=><div key={name}><Equipment kind={["tent","table","chair"][i]}/><b>{name}</b></div>)}</div><div className={"tour-website-callout "+(phase>4?"visible":"")}><Icon name="calendar"/><span>Your dates. Your rentals. One connected booking.</span></div></div>}
function Equipment({kind}:{kind:string}){return <svg viewBox="0 0 160 110" fill="none" aria-hidden="true">{kind==="tent"?<><path d="M15 53 80 13l65 40-65-8Z" fill="#f5edda" stroke="#a7b2a8" strokeWidth="2"/><path d="m80 13 24 38M80 13 48 49" stroke="#d2cab8" strokeWidth="2"/><path d="M15 53v45m130-45v45M80 45v57" stroke="#8b9a93" strokeWidth="3"/><path d="M14 57c10 10 17 1 24 0 8 9 17 9 26 1 10 9 19 9 28 0 9 9 18 8 27-1 8 8 17 9 26-1" stroke="#c4bdab" strokeWidth="2"/></>:kind==="table"?<><ellipse cx="80" cy="42" rx="57" ry="22" fill="#eee9de" stroke="#a8b3ad" strokeWidth="2"/><path d="m45 56 12 44m55-44-12 44M80 65v34" stroke="#89978e" strokeWidth="4"/></>:<><path d="M55 17h49v43H55Z" fill="#fcfcf5" stroke="#a8b3ad" strokeWidth="3"/><path d="m52 60-9 19h70l-10-19Z" fill="#eceee4" stroke="#a8b3ad" strokeWidth="3"/><path d="m47 79-8 26m70-26 8 26M58 60l40 45m4-45-41 45" stroke="#a8b3ad" strokeWidth="3"/></>}</svg>}
export default function ProductTour(){
 const [second,setSecond]=useState(0),[playing,setPlaying]=useState(false),[reduced,setReduced]=useState(false),[visible,setVisible]=useState(false);
 const root=useRef<HTMLDivElement>(null),started=useRef(false);
 const chapter=Math.min(5,Math.floor(second/10)),phase=Math.min(second,59)%10,scene=TOUR_CHAPTERS[chapter];
 useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");const update=()=>{setReduced(media.matches);if(media.matches)setPlaying(false);};update();media.addEventListener("change",update);const observer=new IntersectionObserver(entries=>{const inView=entries[0].isIntersecting;setVisible(inView);if(inView&&!started.current){started.current=true;if(!media.matches)setPlaying(true);}},{threshold:.3});if(root.current)observer.observe(root.current);return()=>{observer.disconnect();media.removeEventListener("change",update);};},[]);
 useEffect(()=>{if(!playing||!visible)return;const timer=window.setInterval(()=>{if(document.hidden)return;setSecond(value=>{if(value>=59){setPlaying(false);return 60;}return value+1;});},1000);return()=>window.clearInterval(timer);},[playing,visible]);
 function jump(index:number){setSecond(index*10);setPlaying(false);}
 const content=chapter===0?<Overview phase={phase}/>:chapter===1?<Orders phase={phase}/>:chapter===2?<OrderDetail phase={phase}/>:chapter===3?<Inventory phase={phase}/>:chapter===4?<Deliveries phase={phase}/>:<Website phase={phase}/>;
 return <div ref={root} className={"product-tour "+(reduced?"tour-reduced":"")} id="product-tour" aria-label="Animated product walkthrough"><div className="tour-window-bar"><div className="tour-window-dots"><i/><i/><i/></div><span>Party Rental CRM <span className="hidden sm:inline">/ product walkthrough</span></span><span className="tour-demo-label">Sample data</span></div><div className="tour-workspace"><aside className="tour-sidebar"><div className="tour-brand"><Icon name="box"/><div><b>Lakeside Events</b><small>DEMO WORKSPACE</small></div></div><nav aria-label="Tour chapters">{TOUR_CHAPTERS.map((step,i)=><button key={step.nav} className={chapter===i?"active":""} onClick={()=>jump(i)} aria-current={chapter===i?"step":undefined}><Icon name={step.icon as IconName}/>{step.nav}</button>)}</nav><div className="tour-account"><span>LE</span><div><b>Sample business</b><small>Owner view</small></div></div></aside><div className="tour-screen"><div className="tour-screen-top"><span>Workspace <i>/</i> <b>{scene.nav}</b></span><span className="tour-sample-pill">Illustrated walkthrough</span></div><div className="tour-scene" key={chapter}><div className="tour-scene-title"><p>{String(chapter+1).padStart(2,"0")} / THE RENTAL WORKFLOW</p><h3>{scene.title}</h3></div>{content}</div></div></div><div className="tour-controls"><div className="tour-caption"><span className="tour-caption-number">0{chapter+1}</span><p>{scene.caption}</p></div><div className="tour-playback"><button onClick={()=>{if(second>=60)setSecond(0);setPlaying(v=>!v);}} aria-label={playing?"Pause product tour":second>=60?"Replay product tour":"Play product tour"}>{playing?<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M6 4v12M14 4v12" stroke="currentColor" strokeWidth="3"/></svg>:<svg viewBox="0 0 20 20" aria-hidden="true"><path d="m6 3 11 7-11 7Z" fill="currentColor"/></svg>}</button><span className="tour-time">{second===60?"1:00":"0:"+String(second).padStart(2,"0")} / 1:00</span><input type="range" min="0" max="60" value={second} onChange={e=>{setSecond(Number(e.target.value));setPlaying(false);}} aria-label="Seek product tour"/><button onClick={()=>{setSecond(0);setPlaying(false);}} aria-label="Restart product tour"><Icon name="clock"/></button></div><div className="tour-mobile-chapters">{TOUR_CHAPTERS.map((step,i)=><button key={step.nav} onClick={()=>jump(i)} aria-pressed={chapter===i}>{step.nav}</button>)}</div></div><p className="tour-disclosure">Animated interface illustration using fictional bookings. No real customer data. No audio needed.</p></div>;
}
