import Link from "next/link";
import { notFound } from "next/navigation";
import { requireCurrentOrganization } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import AssignDriverSelect from "../../deliveries/assign-driver-select";
import OrderTasks from "./OrderTasks";
import OrderStatusSelect from "./OrderStatusSelect";
import OrderPayments from "./OrderPayments";
import PortalLinkButton from "./PortalLinkButton";
import CustomerQuickEdit from "./CustomerQuickEdit";
import DeliveryAddressEditor from "./DeliveryAddressEditor";
import OrderScheduleEditor from "./OrderScheduleEditor";
import OrderItemsEditor from "./OrderItemsEditor";
import Icon from "../../components/Icon";
import {PageHeading,MetricCard,SectionHeading,StatusBadge,money,eventDateLabel} from "../../components/TenantUI";
export default async function OrderDetailPage({params: paramsPromise}:{params:Promise<{id:string}>}){
  const params = await paramsPromise;

 const organization=await requireCurrentOrganization();
 const [order,drivers,catalog]=await Promise.all([
  prisma.order.findFirst({where:{id:params.id,organizationId:organization.id},include:{customer:true,items:{include:{item:true}},orderAddons:true,contract:true,deliveryDriver:true,pickupDriver:true}}),
  prisma.driver.findMany({where:{organizationId:organization.id,isActive:true},orderBy:{name:"asc"}}),
  prisma.item.findMany({where:{organizationId:organization.id},select:{id:true,name:true,cost:true,status:true},orderBy:{name:"asc"}}),
 ]);
 if(!order)notFound();
 const balanceDue=Math.max(0,order.totalAmount-order.amountPaid);
 return <div className="friendly-admin-page is-wide"><Link href="/dashboard/orders" className="inline-flex items-center gap-2 text-xs font-semibold text-[#1a6fd4] hover:underline">← All orders</Link>
 <PageHeading eyebrow="Order workspace" title={order.orderNumber} description={`${order.customer.firstName} ${order.customer.lastName} · ${eventDateLabel(order.eventDate)}`} actions={<><StatusBadge status={order.status}/><OrderStatusSelect orderId={order.id} currentStatus={order.status}/><a href="#payment-history" className="friendly-admin-secondary">Payment / Refund</a><a href="#order-notes" className="friendly-admin-secondary">Note</a><Link href="/dashboard/do-not-rent" className="friendly-admin-secondary">Do Not Rent</Link><Link href={`/dashboard/orders/${order.id}/fulfillment`} className="friendly-admin-primary"><Icon name="box" className="h-4 w-4"/>Fulfillment</Link></>}/>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Order totals"><MetricCard label="Order total" value={money(order.totalAmount)} detail="Rental, fees & tax" icon="orders"/><MetricCard label="Payments received" value={money(order.amountPaid)} detail="Recorded payments" icon="wallet"/><MetricCard label="Balance due" value={money(balanceDue)} detail={balanceDue>0?"Payment still needed":"No balance due"} icon={balanceDue>0?"clock":"check"}/><MetricCard label="Rental items" value={String(order.items.reduce((sum,item)=>sum+item.quantity,0))+" pieces"} detail={order.items.length+" different items"} icon="box"/></section>
 <nav aria-label="Order sections" className="order-parity-jump"><a href="#order-items">Items</a><a href="#payment-history">Payments</a><a href="#order-notes">Notes</a><a href="#order-customer">Customer</a><a href="#order-event">Schedule</a><a href="#order-agreement">Contract</a></nav>
 <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-6">
 <section id="order-items" className="friendly-admin-card !p-0 scroll-mt-28"><SectionHeading title="Rental items" description={`${order.items.reduce((sum,item)=>sum+item.quantity,0)} units across ${order.items.length} line items`}/><div className="overflow-x-auto"><table className="tenant-table"><thead><tr><th>Item</th><th className="text-center">Qty</th><th className="text-right">Unit price</th><th className="text-right">Total</th></tr></thead><tbody>{order.items.map(line=><tr key={line.id}><td><div className="flex min-w-[160px] items-center gap-3">{line.item.picture?<img src={line.item.picture} alt="" className="h-11 w-11 shrink-0 rounded-lg border border-slate-100 object-cover"/>:<span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-400"><Icon name="box"/></span>}<span>{line.item.name}</span></div></td><td className="text-center">{line.quantity}</td><td className="text-right tabular-nums">{money(line.price)}</td><td className="text-right tabular-nums">{money(line.price*line.quantity)}</td></tr>)}{order.orderAddons.map(addon=><tr key={addon.id}><td>+ {addon.name}</td><td className="text-center">—</td><td className="text-right">—</td><td className="text-right tabular-nums">{money(addon.price)}</td></tr>)}</tbody></table></div><OrderItemsEditor orderId={order.id} initialLines={order.items.map(line=>({itemId:line.itemId,quantity:line.quantity,price:line.price}))} catalog={catalog}/><div className="border-t border-slate-100 bg-slate-50/50 p-5"><dl className="ml-auto max-w-xs space-y-3 text-xs text-slate-500">{[["Subtotal",order.subtotal],["Delivery",order.deliveryFee],["Tax",order.taxAmount]].map(([label,value])=><div className="flex justify-between" key={label}><dt>{label}</dt><dd className="tabular-nums">{money(Number(value))}</dd></div>)}<div className="flex justify-between border-t border-slate-200 pt-3 text-sm font-semibold text-slate-900"><dt>Order total</dt><dd>{money(order.totalAmount)}</dd></div></dl></div></section>
 <section id="payment-history" className="friendly-admin-card !p-0 scroll-mt-28"><SectionHeading title="Payments" description="Record payments and review the payment history"/><div className="p-5"><OrderPayments orderId={order.id}/></div></section>
 <PortalLinkButton orderId={order.id}/>
 <section id="order-notes" className="friendly-admin-card !p-0 scroll-mt-28"><SectionHeading title="Order tasks & notes" description="Keep your office and crew on the same page"/><div className="p-5"><OrderTasks orderId={order.id}/></div></section>
 </div><aside className="space-y-6">
 <section id="order-customer" className="friendly-admin-card !p-0 scroll-mt-28"><SectionHeading title="Customer" href={`/dashboard/customers/${order.customer.id}`} label="Profile"/><div className="space-y-3 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-xs font-semibold text-emerald-800">{order.customer.firstName[0]}{order.customer.lastName[0]}</span><p className="text-sm font-semibold text-slate-900">{order.customer.firstName} {order.customer.lastName}</p></div><a href={"mailto:"+order.customer.email} className="block break-all text-xs text-slate-500">{order.customer.email}</a>{order.customer.phone&&<a href={"tel:"+order.customer.phone} className="block text-xs text-slate-500">{order.customer.phone}</a>}<CustomerQuickEdit customer={{id:order.customer.id,firstName:order.customer.firstName,lastName:order.customer.lastName,email:order.customer.email,phone:order.customer.phone,address:order.customer.address,city:order.customer.city,state:order.customer.state,zip:order.customer.zip}}/></div></section>
 <section id="order-event" className="friendly-admin-card !p-0 scroll-mt-28"><SectionHeading title="Event & delivery"/><div className="space-y-4 p-5 text-sm"><div className="flex items-start gap-3"><Icon name="calendar" className="h-4 w-4 text-slate-400"/><div><p className="font-medium text-slate-800">{eventDateLabel(order.eventDate)}</p>{order.eventEndDate&&+order.eventEndDate!==+order.eventDate&&<p className="mt-1 text-xs text-slate-500">Through {eventDateLabel(order.eventEndDate)}</p>}</div></div><div className="flex items-start gap-3"><Icon name="truck" className="h-4 w-4 text-slate-400"/><div><p className="font-medium text-slate-800">{order.deliveryType==="pickup"?"Customer pickup":"Delivery"}</p>{order.deliveryAddress&&<p className="mt-1 text-xs leading-5 text-slate-500">{order.deliveryAddress}</p>}</div></div><OrderScheduleEditor orderId={order.id} eventDate={order.eventDate.toISOString()} eventEndDate={(order.eventEndDate||order.eventDate).toISOString()} deliveryType={order.deliveryType}/><DeliveryAddressEditor orderId={order.id} address={order.deliveryAddress}/><div className="border-t border-slate-100 pt-4"><p className="mb-2 text-xs font-medium text-slate-500">Delivery driver</p><AssignDriverSelect orderId={order.id} drivers={drivers} currentDriverId={order.deliveryDriverId}/></div><Link href={`/dashboard/orders/${order.id}/fulfillment`} className="friendly-admin-secondary w-full">Warehouse & fulfillment<Icon name="arrow" className="h-4 w-4"/></Link></div></section>
 <section id="order-agreement" className="friendly-admin-card !p-0 scroll-mt-28"><SectionHeading title="Rental agreement"/><div className="p-5">{order.contract?.signedAt?<><span className="tenant-badge tenant-badge-green"><Icon name="check" className="h-3 w-3"/>Signed</span><p className="mt-3 text-xs leading-5 text-slate-500">Signed by {order.contract.signatureName} on {eventDateLabel(order.contract.signedAt)}</p>{order.contract.contractText&&<details className="mt-4"><summary className="cursor-pointer text-xs font-semibold text-emerald-700">View signed agreement</summary><div className="mt-3 max-h-64 overflow-y-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600">{order.contract.contractText}</div></details>}</>:<><span className="tenant-badge tenant-badge-amber">Awaiting signature</span><p className="mt-3 text-xs leading-5 text-slate-500">Use the customer portal to share the order and agreement.</p></>}</div></section>
 </aside></div></div>;
}
