import Link from "next/link";
import { notFound } from "next/navigation";
import { requireCurrentOrganization } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import AssignDriverSelect from "../../deliveries/assign-driver-select";
import OrderTasks from "./OrderTasks";
import OrderStatusSelect from "./OrderStatusSelect";
import OrderPayments from "./OrderPayments";

export default async function OrderDetailPage({params}:{params:{id:string}}){
  const organization=await requireCurrentOrganization();
  const[order,drivers]=await Promise.all([
    prisma.order.findFirst({where:{id:params.id,organizationId:organization.id},include:{customer:true,items:{include:{item:true}},orderAddons:true,contract:true,deliveryDriver:true,pickupDriver:true}}),
    prisma.driver.findMany({where:{organizationId:organization.id,isActive:true},orderBy:{name:"asc"}})
  ]);
  if(!order)notFound();
  const balanceDue=order.totalAmount-order.amountPaid;
  return <div className="mx-auto max-w-5xl space-y-6 p-5 sm:p-8">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href="/dashboard/orders" className="text-sm font-bold text-blue-600">← Back to Orders</Link><h1 className="mt-2 text-2xl font-black text-slate-950">Order {order.orderNumber}</h1></div><div className="flex flex-wrap items-center gap-2"><Link href={`/dashboard/orders/${order.id}/fulfillment`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Warehouse & Fulfillment</Link><OrderStatusSelect orderId={order.id} currentStatus={order.status}/></div></div>
    <div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-900">Customer</h2><Link href={`/dashboard/customers/${order.customer.id}`} className="mt-3 block text-sm font-bold text-blue-600">{order.customer.firstName} {order.customer.lastName}</Link><p className="text-sm text-slate-500">{order.customer.email}</p>{order.customer.phone&&<p className="text-sm text-slate-500">{order.customer.phone}</p>}</div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-900">Event & Delivery</h2><p className="mt-3 text-sm text-slate-700">Event date: {order.eventDate.toDateString()}</p><p className="text-sm capitalize text-slate-700">Type: {order.deliveryType}</p>{order.deliveryAddress&&<p className="text-sm text-slate-500">{order.deliveryAddress}</p>}<div className="mt-3"><label className="mb-1 block text-xs text-slate-400">Delivery driver</label><AssignDriverSelect orderId={order.id} drivers={drivers} currentDriverId={order.deliveryDriverId}/></div></div></div>
    <div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-blue-950">Fulfillment control</h2><p className="mt-1 text-xs text-blue-800">Track expected, loaded, returned, damaged and missing quantities for this exact order.</p></div><Link href={`/dashboard/orders/${order.id}/fulfillment`} className="shrink-0 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white">Open fulfillment →</Link></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 font-black text-slate-900">Items</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wide text-slate-400"><th className="py-2">Item</th><th className="py-2">Qty</th><th className="py-2">Price</th></tr></thead><tbody>{order.items.map(oi=><tr key={oi.id} className="border-b last:border-0"><td className="py-3 font-medium">{oi.item.name}</td><td className="py-3">{oi.quantity}</td><td className="py-3">${oi.price.toFixed(2)}</td></tr>)}{order.orderAddons.map(addon=><tr key={addon.id} className="border-b text-slate-500 last:border-0"><td className="py-3">+ {addon.name}</td><td className="py-3">-</td><td className="py-3">${addon.price.toFixed(2)}</td></tr>)}</tbody></table></div><div className="ml-auto mt-4 max-w-xs space-y-1 border-t pt-4 text-sm text-slate-700"><div className="flex justify-between"><span>Subtotal</span><span>${order.subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Delivery fee</span><span>${order.deliveryFee.toFixed(2)}</span></div><div className="flex justify-between"><span>Tax</span><span>${order.taxAmount.toFixed(2)}</span></div><div className="flex justify-between font-black"><span>Total</span><span>${order.totalAmount.toFixed(2)}</span></div><div className="flex justify-between text-slate-500"><span>Paid</span><span>${order.amountPaid.toFixed(2)}</span></div><div className="flex justify-between font-black text-blue-600"><span>Balance due</span><span>${balanceDue.toFixed(2)}</span></div></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 font-black text-slate-900">Payments</h2><OrderPayments orderId={order.id}/></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-2 font-black text-slate-900">Contract</h2>{order.contract?.signedAt?<div><p className="text-sm text-emerald-700">Signed by {order.contract.signatureName} on {order.contract.signedAt.toDateString()}</p>{order.contract.contractText&&<details className="mt-2"><summary className="cursor-pointer text-sm font-bold text-blue-600">View signed contract text</summary><div className="mt-2 max-h-48 overflow-y-auto whitespace-pre-wrap rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600">{order.contract.contractText}</div></details>}</div>:<p className="text-sm text-slate-500">Not signed yet.</p>}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 font-black text-slate-900">Tasks for this order</h2><OrderTasks orderId={order.id}/></div>
  </div>
}
