"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { clearStorefrontCart, getStorefrontCart, updateStorefrontCartQuantity } from "@/lib/storefrontCart";

type Item={id:string;name:string;cost:number;picture:string|null;description?:string|null};
type Addon={id:string;itemId:string;name:string;price:number;isRequired:boolean};
type Bootstrap={item:Item|null;items:Item[];addons:Addon[];depositRule:{type:string;amount:number;isActive:boolean}|null;checkout:{organizationId:string;flatDeliveryFee:number;taxRate:number;contractTerms:string|null;businessName:string;primaryColor:string}};
type Availability={available:number;ok:boolean};
const FALLBACK_TERMS="By signing below, you agree to the rental company's rental terms and accept financial responsibility for the rented equipment during the rental period.";
const inputClass="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-[16px] text-slate-950 outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100";

export default function CheckoutClient({organizationId}:{organizationId:string}){
  const router=useRouter(),params=useSearchParams();
  const isCart=params.get("cart")==="1",directItemId=params.get("itemId");
  const[data,setData]=useState<Bootstrap|null>(null),[pageError,setPageError]=useState(""),[submitting,setSubmitting]=useState(false);
  const[quantities,setQuantities]=useState<Record<string,number>>({}),[selectedAddons,setSelectedAddons]=useState<Record<string,string[]>>({}),[availability,setAvailability]=useState<Record<string,Availability>>({});
  const[eventDate,setEventDate]=useState(""),[eventEndDate,setEventEndDate]=useState(""),[deliveryType,setDeliveryType]=useState<"delivery"|"pickup">("delivery");
  const[couponInput,setCouponInput]=useState(""),[coupon,setCoupon]=useState<{code:string;discountType:string;discountAmount:number}|null>(null),[couponError,setCouponError]=useState(""),[couponBusy,setCouponBusy]=useState(false),[signatureName,setSignatureName]=useState(""),[agree,setAgree]=useState(false);

  useEffect(()=>{
    let itemIds:string[]=[];const initialQty:Record<string,number>={};
    if(isCart){const cart=getStorefrontCart(organizationId);itemIds=cart.map(l=>l.itemId);for(const l of cart)initialQty[l.itemId]=l.quantity;}
    else if(directItemId){itemIds=[directItemId];initialQty[directItemId]=1;}
    if(!itemIds.length){setPageError(isCart?"Your cart is empty. Add rentals before checking out.":"Choose a rental before checking out.");return;}
    setQuantities(initialQty);
    fetch(`/api/storefront/checkout-data?itemIds=${encodeURIComponent(itemIds.join(","))}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load checkout");return b;}).then((b:Bootstrap)=>{setData(b);const required:Record<string,string[]>={};for(const item of b.items)required[item.id]=b.addons.filter(a=>a.itemId===item.id&&a.isRequired).map(a=>a.id);setSelectedAddons(required);}).catch(e=>setPageError(e instanceof Error?e.message:"Unable to load checkout"));
  },[isCart,directItemId,organizationId]);

  useEffect(()=>{
    if(!data||!eventDate){setAvailability({});return;}
    let cancelled=false;const timer=window.setTimeout(async()=>{const pairs=await Promise.all(data.items.map(async item=>{const p=new URLSearchParams({itemId:item.id,start:eventDate,quantity:String(quantities[item.id]||1)});if(eventEndDate)p.set("end",eventEndDate);try{const r=await fetch(`/api/availability?${p}`);if(!r.ok)return[item.id,{available:0,ok:false}] as const;const b=await r.json();return[item.id,b] as const}catch{return[item.id,{available:0,ok:false}] as const}}));if(!cancelled)setAvailability(Object.fromEntries(pairs));},220);return()=>{cancelled=true;window.clearTimeout(timer)};
  },[data,eventDate,eventEndDate,quantities]);

  const totals=useMemo(()=>{if(!data)return{subtotal:0,addons:0,discount:0,tax:0,total:0,due:0,balance:0,delivery:0};const subtotal=data.items.reduce((s,i)=>s+i.cost*(quantities[i.id]||1),0),addons=data.addons.filter(a=>(selectedAddons[a.itemId]||[]).includes(a.id)).reduce((s,a)=>s+a.price,0),delivery=deliveryType==="delivery"?data.checkout.flatDeliveryFee:0,pre=subtotal+addons+delivery,discount=coupon?(coupon.discountType==="fixed"?Math.min(coupon.discountAmount,pre):Math.round(pre*coupon.discountAmount)/100):0,taxable=Math.max(0,subtotal+addons-discount),tax=Math.round(taxable*data.checkout.taxRate)/100,total=Math.max(0,pre-discount+tax),due=data.depositRule?.isActive?(data.depositRule.type==="flat"?Math.min(data.depositRule.amount,total):Math.round(total*data.depositRule.amount)/100):total;return{subtotal,addons,discount,tax,total,due,balance:Math.max(0,total-due),delivery}},[data,quantities,selectedAddons,coupon,deliveryType]);

  function changeQty(itemId:string,next:number){const q=Math.max(1,Math.min(10000,Math.floor(Number(next)||1)));setQuantities(prev=>({...prev,[itemId]:q}));if(isCart)updateStorefrontCartQuantity(organizationId,itemId,q);}
  function toggleAddon(itemId:string,addon:Addon){if(addon.isRequired)return;setSelectedAddons(prev=>{const current=prev[itemId]||[];return{...prev,[itemId]:current.includes(addon.id)?current.filter(id=>id!==addon.id):[...current,addon.id]}})}
  async function applyCoupon(){setCouponError("");if(!couponInput.trim())return;setCouponBusy(true);try{const r=await fetch("/api/coupons/validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:couponInput})}),b=await r.json();if(!r.ok)throw new Error(b.error||"Coupon is not valid");setCoupon(b)}catch(e){setCoupon(null);setCouponError(e instanceof Error?e.message:"Coupon is not valid")}finally{setCouponBusy(false)}}

  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setPageError("");if(!data)return;if(!eventDate)return setPageError("Select your event date.");if(eventEndDate&&eventEndDate<eventDate)return setPageError("The end date cannot be before the event date.");const unavailable=data.items.find(i=>availability[i.id]&&!availability[i.id].ok);if(unavailable)return setPageError(`${unavailable.name} is not available in the requested quantity for those dates.`);if(!signatureName.trim()||!agree)return setPageError("Please sign and accept the rental agreement to continue.");setSubmitting(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:data.items.map(i=>({itemId:i.id,quantity:quantities[i.id]||1,addonIds:selectedAddons[i.id]||[]})),firstName:f.get("firstName"),lastName:f.get("lastName"),email:f.get("email"),phone:f.get("phone"),eventDate,eventEndDate:eventEndDate||null,deliveryType,deliveryAddress:deliveryType==="delivery"?f.get("deliveryAddress"):null,signatureName,couponCode:coupon?.code})}),b=await r.json();if(!r.ok)throw new Error(b.error||"We couldn't complete your booking.");if(b.url)window.location.assign(b.url);else{if(isCart)clearStorefrontCart(organizationId);router.push(`/checkout/success${b.orderId?`?orderId=${b.orderId}&clearCart=${isCart?"1":"0"}`:""}`)}}catch(e){setPageError(e instanceof Error?e.message:"Something went wrong. Please try again.");setSubmitting(false)}}

  if(pageError&&!data)return <main className="mx-auto max-w-xl px-5 py-20"><div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h1 className="font-bold">We couldn't open checkout</h1><p className="mt-2 text-sm">{pageError}</p><button onClick={()=>router.push("/book")} className="mt-5 font-bold underline">Browse rentals</button></div></main>;
  if(!data)return <main className="mx-auto max-w-xl px-5 py-20 text-center text-slate-500">Loading your reservation…</main>;
  const accent=data.checkout.primaryColor||"#2563eb";

  return <main className="min-h-screen bg-slate-50 pb-16"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button onClick={()=>router.back()} className="text-sm font-semibold text-slate-600">← Back</button><div className="text-sm font-black">{data.checkout.businessName}</div><div className="text-xs font-semibold text-slate-400">Secure checkout</div></div></header><div className="mx-auto max-w-6xl px-5 py-8 sm:py-12"><div className="mb-8"><p className="text-sm font-black" style={{color:accent}}>Complete your reservation</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Event details & payment</h1><p className="mt-2 text-slate-600">One reservation for {data.items.length} {data.items.length===1?"rental":"rentals"}. Availability is checked again when you submit.</p></div><form onSubmit={submit} className="grid gap-8 lg:grid-cols-[1fr_380px] lg:items-start"><div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Your rentals</h2><div className="mt-4 divide-y divide-slate-100">{data.items.map(item=>{const itemAddons=data.addons.filter(a=>a.itemId===item.id);return <div key={item.id} className="py-4 first:pt-0 last:pb-0"><div className="flex gap-4">{item.picture?<img src={item.picture} alt="" className="h-20 w-20 rounded-xl object-cover"/>:<div className="h-20 w-20 rounded-xl bg-slate-100"/>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{item.name}</h3><p className="text-sm text-slate-500">${item.cost.toFixed(2)} each</p></div><input type="number" min={1} value={quantities[item.id]||1} onChange={e=>changeQty(item.id,Number(e.target.value))} className="w-20 rounded-lg border border-slate-300 px-2 py-2 text-center text-sm font-black"/></div>{itemAddons.length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{itemAddons.map(a=><label key={a.id} className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-xs"><input type="checkbox" checked={(selectedAddons[item.id]||[]).includes(a.id)} disabled={a.isRequired} onChange={()=>toggleAddon(item.id,a)}/><span className="flex-1 font-semibold">{a.name}{a.isRequired?" · required":""}</span><b>${a.price.toFixed(2)}</b></label>)}</div>}</div></div>{availability[item.id]&&<div className={`mt-3 rounded-lg px-3 py-2 text-xs font-bold ${availability[item.id].ok?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{availability[item.id].ok?"Available for selected dates":`Only ${availability[item.id].available} available`}</div>}</div>})}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">When & how</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Event date<input type="date" required value={eventDate} onChange={e=>setEventDate(e.target.value)} className={inputClass}/></label><label className="text-sm font-semibold">End date <span className="font-normal text-slate-400">optional</span><input type="date" min={eventDate||undefined} value={eventEndDate} onChange={e=>setEventEndDate(e.target.value)} className={inputClass}/></label></div><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={()=>setDeliveryType("delivery")} className={`rounded-xl border p-4 text-left ${deliveryType==="delivery"?"border-blue-500 bg-blue-50":"border-slate-200"}`}><b className="block text-sm">Delivery</b><span className="text-xs text-slate-500">We bring the rentals to the event</span></button><button type="button" onClick={()=>setDeliveryType("pickup")} className={`rounded-xl border p-4 text-left ${deliveryType==="pickup"?"border-blue-500 bg-blue-50":"border-slate-200"}`}><b className="block text-sm">Customer pickup</b><span className="text-xs text-slate-500">Pick up from the rental company</span></button></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Contact {deliveryType==="delivery"?"& delivery":"information"}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">First name<input name="firstName" required autoComplete="given-name" className={inputClass}/></label><label className="text-sm font-semibold">Last name<input name="lastName" required autoComplete="family-name" className={inputClass}/></label><label className="text-sm font-semibold">Email<input name="email" required type="email" autoComplete="email" className={inputClass}/></label><label className="text-sm font-semibold">Phone<input name="phone" type="tel" autoComplete="tel" className={inputClass}/></label>{deliveryType==="delivery"&&<label className="text-sm font-semibold sm:col-span-2">Event / delivery address<input name="deliveryAddress" required autoComplete="street-address" placeholder="Street address, city, state, ZIP" className={inputClass}/></label>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Rental agreement</h2><div className="mt-3 max-h-44 overflow-y-auto whitespace-pre-wrap rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-600">{data.checkout.contractTerms||FALLBACK_TERMS}</div><label className="mt-4 block text-sm font-semibold">Type your full legal name to sign<input value={signatureName} onChange={e=>setSignatureName(e.target.value)} className={inputClass}/></label><label className="mt-4 flex items-start gap-3 text-sm leading-6"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)} className="mt-1 h-4 w-4"/><span>I have read and agree to the rental agreement and authorize this typed signature.</span></label></section>{pageError&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{pageError}</div>}
  </div><aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:sticky lg:top-6 sm:p-6"><h2 className="text-lg font-black">Order summary</h2><div className="mt-4 space-y-3 text-sm">{data.items.map(i=><div key={i.id} className="flex justify-between gap-4"><span className="text-slate-600">{i.name} × {quantities[i.id]||1}</span><span className="font-semibold">${(i.cost*(quantities[i.id]||1)).toFixed(2)}</span></div>)}{totals.addons>0&&<div className="flex justify-between"><span className="text-slate-600">Add-ons</span><span>${totals.addons.toFixed(2)}</span></div>}<div className="flex justify-between"><span className="text-slate-600">{deliveryType==="delivery"?"Delivery":"Customer pickup"}</span><span>{totals.delivery?`$${totals.delivery.toFixed(2)}`:"Included"}</span></div>{totals.discount>0&&<div className="flex justify-between text-emerald-700"><span>Discount</span><span>−${totals.discount.toFixed(2)}</span></div>}{totals.tax>0&&<div className="flex justify-between"><span className="text-slate-600">Tax</span><span>${totals.tax.toFixed(2)}</span></div>}<div className="border-t border-slate-200 pt-3"><div className="flex justify-between text-base font-black"><span>Total</span><span>${totals.total.toFixed(2)}</span></div><div className="mt-3 flex justify-between rounded-xl bg-blue-50 px-3 py-3 font-black text-blue-800"><span>Due today</span><span>${totals.due.toFixed(2)}</span></div>{totals.balance>0&&<div className="mt-2 flex justify-between px-3 text-xs text-slate-500"><span>Remaining balance</span><span>${totals.balance.toFixed(2)}</span></div>}</div></div><div className="mt-5"><div className="flex gap-2"><input value={couponInput} onChange={e=>setCouponInput(e.target.value)} placeholder="Coupon code" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2.5 text-sm uppercase"/><button type="button" disabled={couponBusy} onClick={applyCoupon} className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold">{couponBusy?"…":"Apply"}</button></div>{couponError&&<p className="mt-2 text-xs font-semibold text-red-600">{couponError}</p>}{coupon&&<p className="mt-2 text-xs font-semibold text-emerald-700">{coupon.code} applied</p>}</div><button disabled={submitting} className="mt-6 w-full rounded-xl px-4 py-3.5 text-sm font-black text-white shadow-sm disabled:opacity-50" style={{backgroundColor:accent}}>{submitting?"Securing reservation…":totals.due>0?`Continue to secure payment · $${totals.due.toFixed(2)}`:"Confirm reservation"}</button><p className="mt-3 text-center text-[11px] leading-4 text-slate-400">Inventory is rechecked atomically before the order is created. Your card is handled by Stripe.</p></aside></form></div></main>;
}
