import {NextRequest,NextResponse} from "next/server";
import {randomUUID} from "crypto";
import {prisma} from "@/lib/prisma";
import {requireCurrentOrganization} from "@/lib/tenant";
import {requirePermission,authzErrorResponse} from "@/lib/authz";

type ContactRow={id:string;organizationId:string;customerId:string;name:string;relationship:string|null;email:string|null;phone:string|null;address:string|null;isPrimary:boolean;notes:string|null;createdAt:Date;updatedAt:Date};
async function getCustomer(orgId:string,id:string){return prisma.customer.findFirst({where:{id,organizationId:orgId}})}
export async function GET(req:NextRequest){const org=await requireCurrentOrganization();try{await requirePermission(org.id,"customers.view")}catch(e){return authzErrorResponse(e)}const customerId=new URL(req.url).searchParams.get("customerId");if(!customerId)return NextResponse.json({error:"customerId is required"},{status:400});if(!await getCustomer(org.id,customerId))return NextResponse.json({error:"Customer not found"},{status:404});const contacts=(await prisma.$queryRawUnsafe(`SELECT * FROM "CustomerContact" WHERE "organizationId"=$1 AND "customerId"=$2 ORDER BY "isPrimary" DESC,"createdAt" ASC`,org.id,customerId)) as ContactRow[];return NextResponse.json({contacts})}
export async function POST(req:NextRequest){const org=await requireCurrentOrganization();try{await requirePermission(org.id,"customers.manage")}catch(e){return authzErrorResponse(e)}const b=await req.json(),customerId=String(b.customerId||"");if(!customerId||!await getCustomer(org.id,customerId))return NextResponse.json({error:"Customer not found"},{status:404});const name=String(b.name||"").trim();if(!name)return NextResponse.json({error:"Contact name is required"},{status:400});const id=randomUUID(),isPrimary=!!b.isPrimary;if(isPrimary)await prisma.$executeRawUnsafe(`UPDATE "CustomerContact" SET "isPrimary"=FALSE,"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=$1 AND "customerId"=$2`,org.id,customerId);await prisma.$executeRawUnsafe(`INSERT INTO "CustomerContact" ("id","organizationId","customerId","name","relationship","email","phone","address","isPrimary","notes") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,org.id,customerId,name,b.relationship?String(b.relationship):null,b.email?String(b.email):null,b.phone?String(b.phone):null,b.address?String(b.address):null,isPrimary,b.notes?String(b.notes):null);return NextResponse.json({success:true,id},{status:201})}
export async function PATCH(req:NextRequest){const org=await requireCurrentOrganization();try{await requirePermission(org.id,"customers.manage")}catch(e){return authzErrorResponse(e)}const b=await req.json(),id=String(b.id||"");const rows=await prisma.$queryRawUnsafe<ContactRow[]>(`SELECT * FROM "CustomerContact" WHERE "id"=$1 AND "organizationId"=$2 LIMIT 1`,id,org.id)) as ContactRow[];const c=rows[0];if(!c)return NextResponse.json({error:"Contact not found"},{status:404});const name=typeof b.name==="string"&&b.name.trim()?b.name.trim():c.name,isPrimary=typeof b.isPrimary==="boolean"?b.isPrimary:c.isPrimary;if(isPrimary)await prisma.$executeRawUnsafe(`UPDATE "CustomerContact" SET "isPrimary"=FALSE,"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=$1 AND "customerId"=$2`,org.id,c.customerId);await prisma.$executeRawUnsafe(`UPDATE "CustomerContact" SET "name"=$1,"relationship"=$2,"email"=$3,"phone"=$4,"address"=$5,"isPrimary"=$6,"notes"=$7,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$8 AND "organizationId"=$9`,name,b.relationship!==undefined?(b.relationship?String(b.relationship):null):c.relationship,b.email!==undefined?(b.email?String(b.email):null):c.email,b.phone!==undefined?(b.phone?String(b.phone):null):c.phone,b.address!==undefined?(b.address?String(b.address):null):c.address,isPrimary,b.notes!==undefined?(b.notes?String(b.notes):null):c.notes,id,org.id);return NextResponse.json({success:true})}
export async function DELETE(req:NextRequest){const org=await requireCurrentOrganization();try{await requirePermission(org.id,"customers.manage")}catch(e){return authzErrorResponse(e)}const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id is required"},{status:400});await prisma.$executeRawUnsafe(`DELETE FROM "CustomerContact" WHERE "id"=$1 AND "organizationId"=$2`,id,org.id);return NextResponse.json({success:true})}
