import {requirePlatformAdmin} from '@/lib/admin';
import {prisma} from '@/lib/prisma';
import {ConsoleHeader,Metric,Notice} from '../_components/Console';
import SchedulerSwitch from './SchedulerSwitch';
export const dynamic='force-dynamic';
export default async function WorkerPage(){
 await requirePlatformAdmin('operations');
 const [runs,totals,policies]=await Promise.all([
  prisma.$queryRawUnsafe<Array<{id:string;state:string;startedAt:Date;finishedAt:Date|null;summary:Record<string,unknown>}>>(`SELECT "id","state","startedAt","finishedAt","summary" FROM "PlatformOperationRun" WHERE "kind"='automation.scheduler' ORDER BY "startedAt" DESC LIMIT 30`),
  prisma.$queryRawUnsafe<Array<{enabled:number;unknown:number}>>(`SELECT (SELECT count(*)::int FROM "AutomationSchedulePolicy" WHERE "enabled"=true) AS enabled,(SELECT count(*)::int FROM "AutomationDelivery" WHERE "state"='unknown' OR ("state"='sending' AND "attemptedAt"<CURRENT_TIMESTAMP-INTERVAL '10 minutes')) AS unknown`),
  prisma.$queryRawUnsafe<Array<{organizationId:string;name:string;enabled:boolean;dailyLimit:number;lastCheckedAt:Date|null}>>(`SELECT p."organizationId",o."name",p."enabled",p."dailyLimit",p."lastCheckedAt" FROM "AutomationSchedulePolicy" p JOIN "Organization" o ON o."id"=p."organizationId" ORDER BY p."enabled" DESC,o."name" LIMIT 100`)
 ]);
 const latest=runs[0],fresh=latest&&Date.now()-+latest.startedAt<20*60000;
 return <div className="space-y-6"><ConsoleHeader eyebrow="Unattended operations" title="Automation scheduler">Scheduled booking communication for explicitly opted-in tenants. Each worker pass exits after a bounded batch; no dashboard needs to remain open.</ConsoleHeader><div className="grid gap-4 sm:grid-cols-3"><Metric label="Latest heartbeat" value={!latest?'Not recorded':fresh?latest.state:'Stale'} detail={latest?latest.startedAt.toISOString():'A configured service alone is not proof of a successful scheduled run.'}/><Metric label="Opted-in tenants" value={totals[0].enabled} detail="Only tenant owners can authorize unattended sending."/><Metric label="Uncertain sends needing review" value={totals[0].unknown} detail="Never replayed automatically; inspect the message provider first."/></div><Notice>No bulk opt-in or Send all button. Provider credentials are never changed here. Sending limits reduce volume; they do not guarantee inbox placement. A completed heartbeat may legitimately report zero sends.</Notice><SchedulerSwitch/><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Worker history</h2><div className="mt-4 space-y-3">{runs.map(r=><article key={r.id} className="rounded-lg border p-4"><p className="text-sm font-semibold">{r.state} · {r.startedAt.toISOString()}</p><pre className="mt-2 whitespace-pre-wrap break-words text-xs leading-5 text-slate-600">{JSON.stringify(r.summary,null,2)}</pre></article>)}{!runs.length&&<p className="text-sm text-slate-500">No worker run has been recorded yet.</p>}</div></section><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Tenant schedules</h2><p className="mt-2 text-xs text-slate-500">Up to 100 configured policies. No tenant is opted in during deployment.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{policies.map(p=><article key={p.organizationId} className="rounded-lg border p-4"><h3 className="text-sm font-semibold">{p.name}</h3><p className="mt-2 text-xs text-slate-600">{p.enabled?'Enabled':'Disabled'} · {p.dailyLimit} attempts / 24h</p><p className="mt-1 text-xs text-slate-500">Last checked: {p.lastCheckedAt?.toISOString()||'Not recorded'}</p></article>)}</div></section></div>;
}
