"use client";
import Link from "next/link";
import FeatureUsageTracker from './FeatureUsageTracker';
import {usePathname} from "next/navigation";
import {signOut} from "next-auth/react";
import {useEffect,useRef,useState,type ReactNode} from "react";
import Icon,{type IconName} from "./components/Icon";
type Item={href:string;label:string;icon:IconName;owner?:boolean};
const item=(path:string,label:string,icon:IconName,owner=false):Item=>({href:"/dashboard"+path,label,icon,owner});
const primary:Item[]=[item("","Dashboard","home"),item("/scheduling","Calendar","calendar"),item("/orders","Orders","orders"),item("/customers","Customers","users"),item("/inventory","Inventory","box")];
const groups:{label:string;items:Item[]}[]=[
 {label:"Operations",items:[item("/operations","Operations overview","truck"),item("/deliveries","Deliveries & routes","truck"),item("/dispatch","Dispatch","calendar"),item("/warehouse","Warehouse","box"),item("/returns","Returns & damage","shield"),item("/workforce","Workforce","users"),item("/tasks","Tasks","check")]},
 {label:"Business",items:[item("/reports","Reports","chart"),item("/analytics","Analytics","chart"),item("/marketing","Marketing","sparkle"),item("/automations","Automations","clock"),item("/automations/schedule","Scheduled delivery","clock",true),item("/messages","Messages","mail",true),item("/do-not-rent","Do not rent","shield"),item("/coupons","Coupons","wallet")]},
 {label:"Website",items:[item("/website","Website editor","globe"),item("/pages","Website pages","orders")]},
 {label:"Account",items:[item("/staff","Staff accounts","users",true),item("/roles","Roles & permissions","shield",true),item("/drivers","Drivers","truck",true),item("/message-templates","Message templates","mail",true),item("/activity","Activity log","clock",true),item("/settings/billing","Plan & billing","wallet",true),item("/settings","Settings","settings",true),item("/sessions","Sign-in sessions","shield")]},
];
export default function DashboardNav({showSettings,orgName="Your rental business",userName="Account",role="User",children,supportBanner}:{showSettings:boolean;orgName?:string;userName?:string;role?:string;children?:ReactNode;supportBanner?:ReactNode}){
 const pathname=usePathname(),[open,setOpen]=useState(false),[navQuery,setNavQuery]=useState("");
 const drawer=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const permitted=[...primary,...groups.flatMap(g=>g.items)].filter(i=>!i.owner||showSettings);
 const current=permitted.filter(i=>pathname===i.href||(i.href!=="/dashboard"&&pathname.startsWith(i.href+"/"))).sort((a,b)=>b.href.length-a.href.length)[0];
 const active=(i:Item)=>current?.href===i.href;
 useEffect(()=>{setOpen(false);setNavQuery("");},[pathname]);
 useEffect(()=>{const dialog=drawer.current;if(open&&!dialog?.open)dialog?.showModal();if(!open&&dialog?.open)dialog.close();if(open){const before=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=before;};}},[open]);
 const navLink=(i:Item)=><Link key={i.href} href={i.href} onClick={()=>setOpen(false)} aria-current={active(i)?"page":undefined} className={"tenant-nav-link "+(active(i)?"is-active":"")}><Icon name={i.icon} className="h-[17px] w-[17px] shrink-0"/><span>{i.label}</span></Link>;
 const navigation=<><Link href="/dashboard" className="mb-7 flex min-w-0 items-center gap-3 px-2" onClick={()=>setOpen(false)}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-700 text-white"><Icon name="box" className="h-5 w-5"/></span><span className="min-w-0"><span className="block truncate text-sm font-bold text-slate-900">{orgName}</span><span className="mt-0.5 block text-[10px] font-semibold uppercase tracking-[.12em] text-slate-500">Rental Admin</span></span></Link>
 <label className="mb-4 flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-slate-400"><Icon name="search" className="h-4 w-4"/><input aria-label="Find a tool" value={navQuery} onChange={e=>setNavQuery(e.target.value)} placeholder="Find a tool…" className="min-w-0 w-full bg-transparent text-xs text-slate-700 outline-none placeholder:text-slate-400"/></label>
 <nav aria-label="Tenant navigation" className="flex-1 space-y-5">{navQuery.trim()?<div className="space-y-1">{permitted.filter(i=>i.label.toLowerCase().includes(navQuery.toLowerCase())).map(navLink)}{!permitted.some(i=>i.label.toLowerCase().includes(navQuery.toLowerCase()))&&<p className="px-3 text-sm text-slate-400">No matching tools.</p>}</div>:<><div className="space-y-1">{primary.map(navLink)}</div>{groups.map(g=>{const entries=g.items.filter(i=>!i.owner||showSettings);if(!entries.length)return null;return <details key={g.label+pathname} open={g.label==="Operations"||entries.some(active)} className="tenant-nav-group"><summary className="mb-1 flex cursor-pointer list-none items-center justify-between px-2 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">{g.label}<Icon name="down" className="h-3 w-3"/></summary><div className="space-y-1">{entries.map(navLink)}</div></details>})}</>}</nav>
 <div className="mt-5 border-t border-slate-200 pt-4"><div className="flex items-center gap-3 px-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-800">{userName.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-800">{userName}</p><p className="mt-0.5 text-[11px] capitalize text-slate-500">{role}</p></div><button title="Sign out" aria-label="Sign out" onClick={()=>signOut({callbackUrl:"/login"})} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><Icon name="exit" className="h-4 w-4"/></button></div></div></>;
 return <div className="tenant-app"><FeatureUsageTracker path={pathname} enabled={!supportBanner}/><a href="#tenant-main" className="tenant-skip">Skip to content</a><aside className="tenant-sidebar hidden lg:flex">{navigation}</aside>
 <dialog ref={drawer} className="tenant-drawer" onCancel={()=>setOpen(false)} onClose={()=>{setOpen(false);trigger.current?.focus();}} aria-label="Workspace navigation"><button onClick={()=>setOpen(false)} className="mb-4 ml-auto block rounded-lg p-2 text-slate-700" aria-label="Close navigation"><Icon name="close"/></button>{navigation}</dialog>
 <div className="min-w-0 flex-1"><div className="sticky top-0 z-40">{supportBanner}<header className="tenant-topbar"><div className="flex min-w-0 items-center gap-3"><button ref={trigger} type="button" onClick={()=>setOpen(true)} className="rounded-lg border border-slate-200 p-2 lg:hidden" aria-label="Open navigation" aria-expanded={open} aria-haspopup="dialog"><Icon name="menu"/></button><span className="truncate text-[15px] font-bold text-slate-900">{current?.label||"Dashboard"}</span></div><form action="/dashboard/orders" className="hidden w-64 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 md:flex"><Icon name="search" className="h-4 w-4 text-slate-400"/><input name="q" aria-label="Search orders or customers" placeholder="Search orders, customers..." className="w-full min-w-0 bg-transparent text-xs outline-none"/></form><Link href="/dashboard/orders/new" className="tenant-button tenant-button-primary !px-3 !py-2 text-xs"><Icon name="plus" className="h-4 w-4"/><span>Create Order</span></Link></header></div>
 <main id="tenant-main" tabIndex={-1} className="tenant-content">{children}</main>
 <nav className="tenant-mobile-nav lg:hidden" aria-label="Quick navigation">{primary.slice(0,3).map(i=><Link key={i.href} href={i.href} aria-current={active(i)?"page":undefined} className={active(i)?"text-emerald-700":"text-slate-500"}><Icon name={i.icon}/><span>{i.label}</span></Link>)}<button onClick={()=>setOpen(true)} className="text-slate-500" aria-label="Open all tools"><Icon name="menu"/><span>All tools</span></button></nav></div></div>;
}
