import { requireCurrentOrganization } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import HomeCalendar from "./HomeCalendar";
import HomeTasks from "./HomeTasks";
import HomeWeather from "./HomeWeather";
import HomeScreen from "./HomeScreen";
import HomeMeetings from "./HomeMeetings";
import BestSellersChart from "./BestSellersChart";
import MonthlyPaymentsChart from "./MonthlyPaymentsChart";
import { getOrganizationWeather } from "@/lib/weather";

function monthRange(year:number,month:number){return{start:new Date(year,month,1),end:new Date(year,month+1,1)}}
function startOfToday(){const d=new Date();d.setHours(0,0,0,0);return d}
function endOfToday(){const d=new Date();d.setHours(23,59,59,999);return d}
const statusTone=(status:string)=>status.toLowerCase().includes("cancel")?"bg-red-50 text-red-700":status.toLowerCase().includes("complete")?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700";

export default async function DashboardHomePage({searchParams}:{searchParams:{year?:string;month?:string}}){
 const organization=await requireCurrentOrganization(); const now=new Date();
 const year=searchParams.year?parseInt(searchParams.year,10):now.getFullYear(); const month=searchParams.month?parseInt(searchParams.month,10):now.getMonth();
 const {start,end}=monthRange(year,month); const sixtyDaysAgo=new Date(now.getTime()-60*86400000); const twelveMonthsAgo=new Date(now.getFullYear(),now.getMonth()-11,1);
 const [itemCount,highValueItemCount,monthOrders,todaysOrders,recentOrderItems,recentOrders,upcomingOrders,weather,paymentOrders]=await Promise.all([
  prisma.item.count({where:{organizationId:organization.id}}),prisma.item.count({where:{organizationId:organization.id,cost:{gte:65}}}),
  prisma.order.findMany({where:{organizationId:organization.id,eventDate:{gte:start,lt:end}},select:{id:true,status:true,deliveryType:true,eventDate:true},orderBy:{eventDate:"asc"}}),
  prisma.order.findMany({where:{organizationId:organization.id,updatedAt:{gte:startOfToday(),lte:endOfToday()}},select:{amountPaid:true}}),
  prisma.orderItem.findMany({where:{order:{organizationId:organization.id,createdAt:{gte:sixtyDaysAgo}}},select:{quantity:true,item:{select:{name:true}}}}),
  prisma.order.findMany({where:{organizationId:organization.id},orderBy:{createdAt:"desc"},take:5,include:{customer:true}}),
  prisma.order.findMany({where:{organizationId:organization.id,eventDate:{gte:now}},orderBy:{eventDate:"asc"},take:5,include:{customer:true}}),
  getOrganizationWeather({city:organization.city,state:organization.state,zip:organization.zip,address:organization.address}),
  prisma.order.findMany({where:{organizationId:organization.id,createdAt:{gte:twelveMonthsAgo},amountPaid:{gt:0}},select:{amountPaid:true,createdAt:true}})
 ]);
 const collectedToday=todaysOrders.reduce((s,o)=>s+o.amountPaid,0); const bestSellerMap=new Map<string,number>(); recentOrderItems.forEach(oi=>{const n=oi.item?.name||"Unknown item";bestSellerMap.set(n,(bestSellerMap.get(n)||0)+oi.quantity)}); const bestSellers=Array.from(bestSellerMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,qty])=>({name,qty}));
 const monthlyPayments:{label:string;total:number}[]=[]; for(let i=11;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);monthlyPayments.push({label:d.toLocaleDateString("en-US",{month:"short",year:"2-digit"}),total:0})} paymentOrders.forEach(o=>{const d=new Date(o.createdAt);const ago=(now.getFullYear()-d.getFullYear())*12+(now.getMonth()-d.getMonth());const idx=11-ago;if(idx>=0&&idx<12)monthlyPayments[idx].total+=o.amountPaid}); const hasMonthlyPayments=monthlyPayments.some(p=>p.total>0);
 const nextEvent=upcomingOrders[0];
 return <div className="space-y-7 pb-10">
  <section className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-7 text-white shadow-xl sm:px-8 sm:py-9">
   <div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-blue-500/25 blur-3xl"/><div className="absolute bottom-0 left-1/3 h-32 w-72 bg-emerald-400/10 blur-3xl"/>
   <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-blue-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Live operations</div><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Good {now.getHours()<12?"morning":now.getHours()<17?"afternoon":"evening"}.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">Here’s what is happening across {organization.name} right now.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/orders/new" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold shadow-lg shadow-blue-950/30 transition hover:-translate-y-0.5 hover:bg-blue-500">+ New order</Link><Link href="/dashboard/inventory" className="rounded-xl border border-slate-700 bg-white/5 px-4 py-2.5 text-sm font-bold transition hover:bg-white/10">Inventory</Link><Link href="/dashboard/deliveries" className="rounded-xl border border-slate-700 bg-white/5 px-4 py-2.5 text-sm font-bold transition hover:bg-white/10">Deliveries</Link></div></div>
  </section>
  {itemCount===0&&<div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-sm"><span className="font-bold">Finish setting up your business.</span> <Link href="/onboarding" className="font-bold text-indigo-700 underline">Complete onboarding →</Link></div>}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
   {[{label:"Collected today",value:`$${collectedToday.toFixed(2)}`,sub:`${todaysOrders.length} updated orders`,tone:"text-emerald-600"},{label:"Upcoming events",value:String(upcomingOrders.length),sub:nextEvent?`Next ${new Date(nextEvent.eventDate).toLocaleDateString()}`:"Nothing scheduled",tone:"text-blue-600"},{label:"Inventory",value:String(itemCount),sub:`${highValueItemCount} items valued $65+`,tone:"text-violet-600"},{label:"This month",value:String(monthOrders.length),sub:"events on calendar",tone:"text-amber-600"}].map((card,i)=><div key={card.label} className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><div className={`text-xs font-black uppercase tracking-[.14em] ${card.tone}`}>{card.label}</div><div className="mt-2 text-3xl font-black tracking-tight text-slate-950">{card.value}</div><div className="mt-1 text-sm text-slate-500">{card.sub}</div><div className="absolute bottom-0 left-0 h-1 w-0 bg-slate-900 transition-all duration-500 group-hover:w-full"/></div>)}
  </section>
  <section className="grid grid-cols-1 gap-6 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2"><HomeCalendar year={year} month={month} orders={monthOrders.map(o=>({id:o.id,status:o.status,deliveryType:o.deliveryType,eventDate:o.eventDate.toISOString()}))}/><div className="grid gap-6 lg:grid-cols-2"><HomeMeetings contactEmail={organization.contactEmail}/><HomeScreen/></div></div><div className="space-y-6"><HomeTasks/><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="font-black text-slate-900">Best sellers</h3><span className="text-xs font-semibold text-slate-400">60 days</span></div>{bestSellers.length===0?<p className="text-sm text-slate-400">No rental activity yet.</p>:<BestSellersChart data={bestSellers}/>}</div><HomeWeather weather={weather}/></div></section>
  <section className="grid gap-6 lg:grid-cols-2">
   <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-black text-slate-950">Recent orders</h2><p className="mt-1 text-xs text-slate-500">Newest activity across your business</p></div><Link href="/dashboard/orders" className="text-sm font-bold text-blue-600">View all →</Link></div>{recentOrders.length===0?<div className="p-8 text-center text-sm text-slate-500">No orders yet.</div>:<div className="divide-y divide-slate-100">{recentOrders.map(order=><Link key={order.id} href={`/dashboard/orders/${order.id}`} className="flex items-center justify-between gap-4 px-6 py-4 transition hover:bg-slate-50"><div className="min-w-0"><p className="font-bold text-slate-900">#{order.orderNumber.slice(-6)}</p><p className="truncate text-xs text-slate-500">{order.customer?`${order.customer.firstName} ${order.customer.lastName}`:"No customer"}</p></div><div className="text-right"><p className="font-bold text-slate-900">${order.totalAmount.toFixed(2)}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold capitalize ${statusTone(order.status)}`}>{order.status}</span></div></Link>)}</div>}</div>
   <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-black text-slate-950">Upcoming events</h2><p className="mt-1 text-xs text-slate-500">What your team needs to prepare for</p></div><Link href="/dashboard/deliveries" className="text-sm font-bold text-blue-600">Operations →</Link></div>{upcomingOrders.length===0?<div className="p-8 text-center text-sm text-slate-500">No upcoming events.</div>:<div className="divide-y divide-slate-100">{upcomingOrders.map(order=><Link key={order.id} href={`/dashboard/orders/${order.id}`} className="flex items-center justify-between gap-4 px-6 py-4 transition hover:bg-slate-50"><div><p className="font-bold text-slate-900">{new Date(order.eventDate).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</p><p className="text-xs text-slate-500">{order.customer?`${order.customer.firstName} ${order.customer.lastName}`:"No customer"}</p></div><div className="text-right"><p className="text-sm font-bold text-slate-900">#{order.orderNumber.slice(-6)}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold capitalize ${statusTone(order.status)}`}>{order.status}</span></div></Link>)}</div>}</div>
  </section>
  <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5"><h2 className="font-black text-slate-950">Payments received</h2><p className="mt-1 text-sm text-slate-500">12-month collection trend</p></div>{!hasMonthlyPayments?<p className="text-sm text-slate-400">No payments recorded in the last 12 months.</p>:<MonthlyPaymentsChart data={monthlyPayments}/>}</section>
 </div>
}
