import { requireCurrentOrganization } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import HomeCalendar from "./HomeCalendar";
import HomeTasks from "./HomeTasks";
import BestSellersChart from "./BestSellersChart";

function monthRange(year:number,month:number){return{start:new Date(year,month,1),end:new Date(year,month+1,1)}}
function dayStart(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function dayEnd(d=new Date()){const x=new Date(d);x.setHours(23,59,59,999);return x}
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const tone=(s:string)=>s.toLowerCase().includes("cancel")?"bg-rose-50 text-rose-700 ring-rose-100":s.toLowerCase().includes("complete")||s.toLowerCase().includes("paid")?"bg-emerald-50 text-emerald-700 ring-emerald-100":"bg-blue-50 text-blue-700 ring-blue-100";
const fmt=(d:Date)=>new Date(d).toLocaleDateString("en-US",{month:"short",day:"numeric"});

export default async function DashboardHomePage({searchParams}:{searchParams:{year?:string;month?:string}}){
 const organization=await requireCurrentOrganization(); const now=new Date();
 const year=searchParams.year?parseInt(searchParams.year,10):now.getFullYear(); const month=searchParams.month?parseInt(searchParams.month,10):now.getMonth(); const {start,end}=monthRange(year,month); const sixtyDaysAgo=new Date(now.getTime()-60*86400000);
 const [itemCount,monthOrders,todayEvents,recentOrderItems,recentOrders,upcomingOrders]=await Promise.all([
  prisma.item.count({where:{organizationId:organization.id}}),
  prisma.order.findMany({where:{organizationId:organization.id,eventDate:{gte:start,lt:end}},select:{id:true,status:true,deliveryType:true,eventDate:true},orderBy:{eventDate:"asc"}}),
  prisma.order.findMany({where:{organizationId:organization.id,eventDate:{gte:dayStart(),lte:dayEnd()}},include:{customer:true},orderBy:{eventDate:"asc"}}),
  prisma.orderItem.findMany({where:{order:{organizationId:organization.id,createdAt:{gte:sixtyDaysAgo}}},select:{quantity:true,item:{select:{name:true}}}}),
  prisma.order.findMany({where:{organizationId:organization.id},orderBy:{createdAt:"desc"},take:6,include:{customer:true}}),
  prisma.order.findMany({where:{organizationId:organization.id,eventDate:{gte:now}},orderBy:{eventDate:"asc"},take:8,include:{customer:true}})
 ]);
 const activeRecent=recentOrders.filter(o=>!o.status.toLowerCase().includes("cancel"));
 const collectedToday=recentOrders.filter(o=>new Date(o.updatedAt)>=dayStart()).reduce((s,o)=>s+o.amountPaid,0);
 const openBalance=upcomingOrders.reduce((s,o)=>s+Math.max(0,o.totalAmount-o.amountPaid),0);
 const deliveriesToday=todayEvents.filter(o=>o.deliveryType?.toLowerCase().includes("deliver")).length;
 const pickupsToday=todayEvents.filter(o=>o.deliveryType?.toLowerCase().includes("pickup")).length;
 const attention=upcomingOrders.filter(o=>o.totalAmount-o.amountPaid>0).slice(0,5);
 const bestSellerMap=new Map<string,number>(); recentOrderItems.forEach(oi=>{const n=oi.item?.name||"Unknown";bestSellerMap.set(n,(bestSellerMap.get(n)||0)+oi.quantity)}); const bestSellers=Array.from(bestSellerMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,qty])=>({name,qty}));
 const greeting=now.getHours()<12?"morning":now.getHours()<17?"afternoon":"evening";
 return <div className="space-y-5 pb-10">
  <section className="relative overflow-hidden rounded-[28px] border border-slate-800 bg-slate-950 px-6 py-7 text-white shadow-xl sm:px-8">
   <div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_top_right,rgba(37,99,235,.28),transparent_58%)]"/>
   <div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.18em] text-emerald-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Today · {now.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</div><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Good {greeting}, {organization.name}.</h1><p className="mt-2 text-sm text-slate-400">Your operation at a glance. Handle what needs attention, then get back to the event.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/orders/new" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black shadow-lg shadow-blue-950/40 transition hover:-translate-y-0.5 hover:bg-blue-500">＋ New order</Link><Link href="/dashboard/deliveries" className="rounded-xl border border-slate-700 bg-white/5 px-4 py-2.5 text-sm font-bold hover:bg-white/10">Dispatch</Link><Link href="/dashboard/inventory" className="rounded-xl border border-slate-700 bg-white/5 px-4 py-2.5 text-sm font-bold hover:bg-white/10">Inventory</Link></div></div>
  </section>

  {itemCount===0&&<div className="flex items-center justify-between gap-4 rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-sm"><div><b>Finish your setup</b><span className="ml-2 text-slate-600">Add inventory and publish your storefront.</span></div><Link href="/onboarding" className="shrink-0 font-black text-indigo-700">Continue →</Link></div>}

  <section className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">
   {[{icon:"$",label:"Collected",value:money(collectedToday),sub:"today",c:"text-emerald-600 bg-emerald-50"},{icon:"▣",label:"Events",value:String(todayEvents.length),sub:"today",c:"text-blue-600 bg-blue-50"},{icon:"→",label:"Deliveries",value:String(deliveriesToday),sub:"today",c:"text-indigo-600 bg-indigo-50"},{icon:"←",label:"Pickups",value:String(pickupsToday),sub:"today",c:"text-violet-600 bg-violet-50"},{icon:"$",label:"Open balance",value:money(openBalance),sub:"upcoming",c:"text-amber-700 bg-amber-50"},{icon:"□",label:"Inventory",value:String(itemCount),sub:"rental items",c:"text-slate-700 bg-slate-100"}].map(x=><div key={x.label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`flex h-8 w-8 items-center justify-center rounded-lg text-sm font-black ${x.c}`}>{x.icon}</div><div className="mt-3 text-2xl font-black tracking-tight text-slate-950">{x.value}</div><div className="mt-1 text-[11px] font-black uppercase tracking-wide text-slate-600">{x.label}</div><div className="text-[10px] text-slate-400">{x.sub}</div></div>)}
  </section>

  <section className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]">
   <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-black text-slate-950">Next up</h2><p className="text-xs text-slate-500">Upcoming events your team is preparing for</p></div><Link href="/dashboard/deliveries" className="text-xs font-black text-blue-600">Open operations →</Link></div>{upcomingOrders.length===0?<div className="p-10 text-center"><div className="text-2xl">✓</div><b className="mt-2 block">Nothing scheduled yet</b><p className="mt-1 text-sm text-slate-400">New bookings will appear here.</p></div>:<div className="divide-y divide-slate-100">{upcomingOrders.slice(0,6).map((o,i)=>{const bal=Math.max(0,o.totalAmount-o.amountPaid);return <Link key={o.id} href={`/dashboard/orders/${o.id}`} className="grid grid-cols-[52px_1fr_auto] items-center gap-3 px-5 py-3.5 transition hover:bg-slate-50"><div className={`flex h-11 w-11 flex-col items-center justify-center rounded-xl ${i===0?'bg-blue-600 text-white':'bg-slate-100 text-slate-700'}`}><span className="text-[9px] font-black uppercase">{new Date(o.eventDate).toLocaleDateString("en-US",{month:"short"})}</span><span className="text-base font-black leading-none">{new Date(o.eventDate).getDate()}</span></div><div className="min-w-0"><div className="flex items-center gap-2"><b className="truncate text-sm text-slate-900">{o.customer?`${o.customer.firstName} ${o.customer.lastName}`:`Order #${o.orderNumber.slice(-6)}`}</b><span className={`hidden rounded-full px-2 py-0.5 text-[9px] font-black capitalize ring-1 sm:inline-flex ${tone(o.status)}`}>{o.status}</span></div><p className="mt-1 text-[11px] text-slate-500">#{o.orderNumber.slice(-6)} · {o.deliveryType||"Event order"}</p></div><div className="text-right"><b className="text-sm text-slate-900">{money(o.totalAmount)}</b>{bal>0?<p className="text-[10px] font-bold text-amber-600">{money(bal)} due</p>:<p className="text-[10px] font-bold text-emerald-600">Paid</p>}</div></Link>})}</div>}</div>
   <div className="space-y-5"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><div className="flex items-center justify-between"><h2 className="font-black text-slate-950">Needs attention</h2>{attention.length>0&&<span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-black text-amber-700">{attention.length} OPEN</span>}</div><p className="text-xs text-slate-500">Money and orders to follow up on</p></div>{attention.length===0?<div className="p-8 text-center"><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-emerald-50 font-black text-emerald-600">✓</div><b className="mt-3 block text-sm">You're caught up</b><p className="mt-1 text-xs text-slate-400">No upcoming balances need attention.</p></div>:<div className="divide-y divide-slate-100">{attention.map(o=><Link key={o.id} href={`/dashboard/orders/${o.id}`} className="flex items-center justify-between gap-3 px-5 py-3 hover:bg-amber-50/40"><div className="min-w-0"><b className="block truncate text-xs text-slate-900">{o.customer?`${o.customer.firstName} ${o.customer.lastName}`:`#${o.orderNumber.slice(-6)}`}</b><span className="text-[10px] text-slate-400">Event {fmt(o.eventDate)}</span></div><div className="text-right"><b className="text-xs text-amber-700">{money(o.totalAmount-o.amountPaid)} due</b><div className="text-[9px] font-bold text-blue-600">Open →</div></div></Link>)}</div>}</div><HomeTasks/></div>
  </section>

  <details className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between px-5 py-4"><div><h2 className="font-black text-slate-950">Calendar</h2><p className="text-xs text-slate-500">{monthOrders.length} events this month · expand for full month</p></div><span className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-600 group-open:hidden">Open calendar ↓</span><span className="hidden rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-600 group-open:inline">Close ↑</span></summary><div className="border-t border-slate-100 p-3"><HomeCalendar year={year} month={month} orders={monthOrders.map(o=>({id:o.id,status:o.status,deliveryType:o.deliveryType,eventDate:o.eventDate.toISOString()}))}/></div></details>

  <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
   <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-black text-slate-950">Recent orders</h2><p className="text-xs text-slate-500">Latest customer activity</p></div><Link href="/dashboard/orders" className="text-xs font-black text-blue-600">View all →</Link></div>{recentOrders.length===0?<p className="p-8 text-sm text-slate-400">No orders yet.</p>:<div className="grid sm:grid-cols-2">{recentOrders.slice(0,6).map(o=><Link key={o.id} href={`/dashboard/orders/${o.id}`} className="flex items-center justify-between border-b border-slate-100 px-5 py-3.5 sm:odd:border-r hover:bg-slate-50"><div className="min-w-0"><b className="text-xs text-slate-900">#{o.orderNumber.slice(-6)}</b><p className="truncate text-[10px] text-slate-500">{o.customer?`${o.customer.firstName} ${o.customer.lastName}`:"No customer"}</p></div><div className="text-right"><b className="text-xs">{money(o.totalAmount)}</b><p className={`text-[9px] font-bold capitalize ${o.status.toLowerCase().includes("cancel")?'text-rose-600':'text-blue-600'}`}>{o.status}</p></div></Link>)}</div>}</div>
   <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black text-slate-950">Top rentals</h2><p className="text-xs text-slate-500">Last 60 days</p></div><Link href="/dashboard/reports" className="text-xs font-black text-blue-600">Reports →</Link></div>{bestSellers.length>0?<div className="mt-5"><BestSellersChart data={bestSellers}/></div>:<div className="py-10 text-center text-sm text-slate-400">Rental trends will appear after orders come in.</div>}</div>
  </section>
 </div>
}
